### ISSUE TITLE
CODE RUB: Switch DateTime Broker order with Logging IF DateTimeBroker is last

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#1008]
The order of dependencies relies heavily on the priority for business flow. Which means that an entity broker comes before everything else. an entity broker is like `StorageBroker`.
And then comes utility brokers. These brokers some of them are for business flow requirements like `DateTimeBroker` where we ensure that the request datetime stamp is recent.
And the other utility broker is `LoggingBroker` which is only used to be able to trace issues in the system.

We honor dependencies that are more targeting the business flow and leave the less priority dependencies at the very end of our instantiation process to keep the focus on the business needs. Here's an example:

In the `StudentGuardianService.cs` file you'll see the following pattern:

```csharp
        private readonly IStorageBroker storageBroker;
        private readonly ILoggingBroker loggingBroker;
        private readonly IDateTimeBroker dateTimeBroker;

        public StudentGuardianService(
            IStorageBroker storageBroker,
            ILoggingBroker loggingBroker,
            IDateTimeBroker dateTimeBroker)
        {
            this.storageBroker = storageBroker;
            this.loggingBroker = loggingBroker;
            this.dateTimeBroker = dateTimeBroker;
        }
...
```

We need to change this pattern into the following:

```csharp
        private readonly IStorageBroker storageBroker;
        private readonly IDateTimeBroker dateTimeBroker;
        private readonly ILoggingBroker loggingBroker;

        public StudentGuardianService(
            IStorageBroker storageBroker,
            IDateTimeBroker dateTimeBroker,
            ILoggingBroker loggingBroker)
        {
            this.storageBroker = storageBroker;
            this.dateTimeBroker = dateTimeBroker;
            this.loggingBroker = loggingBroker;
        }

...

```

On the Tests.Unit project we also need to change for the same service as follows:

```csharp
        private readonly Mock<IStorageBroker> storageBrokerMock;
        private readonly Mock<ILoggingBroker> loggingBrokerMock;
        private readonly Mock<IDateTimeBroker> dateTimeBrokerMock;
        private readonly IStudentGuardianService studentGuardianService;

        public StudentGuardianServiceTests()
        {
            this.storageBrokerMock = new Mock<IStorageBroker>();
            this.loggingBrokerMock = new Mock<ILoggingBroker>();
            this.dateTimeBrokerMock = new Mock<IDateTimeBroker>();

            this.studentGuardianService = new StudentGuardianService(
                storageBroker: this.storageBrokerMock.Object,
                loggingBroker: this.loggingBrokerMock.Object,
                dateTimeBroker: this.dateTimeBrokerMock.Object);
        }

...
```

We need to change that pattern into:

```csharp

        private readonly Mock<IStorageBroker> storageBrokerMock;
        private readonly Mock<IDateTimeBroker> dateTimeBrokerMock;
        private readonly Mock<ILoggingBroker> loggingBrokerMock;
        private readonly IStudentGuardianService studentGuardianService;

        public StudentGuardianServiceTests()
        {
            this.storageBrokerMock = new Mock<IStorageBroker>();
            this.dateTimeBrokerMock = new Mock<IDateTimeBroker>();
            this.loggingBrokerMock = new Mock<ILoggingBroker>();

            this.studentGuardianService = new StudentGuardianService(
                storageBroker: this.storageBrokerMock.Object,
                dateTimeBroker: this.dateTimeBrokerMock.Object,
                loggingBroker: this.loggingBrokerMock.Object);
        }

..

```

Find similar patterns across the entirety of `OtripleS` project and create PRs with the following titles:
`CODE RUB: Replace DateTimeBroker order with LoggingBroker`

**Comment by hassanhabib** [comment]
This issue is assigned to @KFitz114

**Comment by KFitz114** [comment]
I found something similar to this in: OtripleS.Web.Api.Tests.Unit.Services.Foundations.Assignments -> Exceptions.RetrieveAll.cs

 this.storageBrokerMock.Verify(broker =>
                broker.SelectAllAssignments(),
                    Times.Once);

            this.loggingBrokerMock.Verify(broker =>
                broker.LogError(It.Is(SameExceptionAs(
                    expectedAssignmentServiceException))),
                        Times.Once);

            this.dateTimeBrokerMock.Verify(broker =>
                broker.GetCurrentDateTime(),
                    Times.Never);

            this.storageBrokerMock.VerifyNoOtherCalls();
            this.loggingBrokerMock.VerifyNoOtherCalls();
            this.dateTimeBrokerMock.VerifyNoOtherCalls();

Does this need to be re-ordered to the same as the services in the Web.Api folder?
