### ISSUE TITLE
issue With studentSemasterCourseId

### ISSUE THREAD

**Issue by syedib** [hassanhabib/OtripleS#104]
@hassanhabib 

actually we don't have studentSemasterCourseId in StudentSemasterCourse Table, We are using studentSemasterCourseId to fetch a single record in StudentSemasterCourse broker so in order to fetch single record we suppose to use StudentId and SemesterCourseId together, am I correct?

![image](https://user-images.githubusercontent.com/7100721/90040199-4adf6f80-dce5-11ea-8305-985a08ccf1bc.png)

![image](https://user-images.githubusercontent.com/7100721/90040162-3f8c4400-dce5-11ea-84f6-7508cc258a23.png)

**Comment by AgentEnder** [comment]
In my PR I treated SemesterCourseId and StudentId as a joint primary key, and it was accepted so I assume that was the correct route.

**Comment by syedib** [comment]
> StudentId as

Yes we should use Composite key to fetch single record

**Comment by hassanhabib** [comment]
@syedib  what @AgentEnder  - composite key for retrieval
