### ISSUE TITLE
Discuss User Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#107]
We want to build a User Model to allow tracking the created by and updated by Ids on the system, here's an initial model to work with:

```csharp
public class User : IAuditable {
    public Guid Id {get; set;}
    public string Name {get; set;}
    public UserStatus Status {get; set;}
    public DateTimeOffset CreatedDate {get; set;}
    public DateTimeOffset UpdatedDate {get; set;}
}


public enum UserStatus {
    Activated,
    Deactivated
}
```

**Comment by tobidub** [comment]
Do we want to use something like IdentityServer4?

**Comment by syedib** [comment]
do we need username or email

**Comment by AgentEnder** [comment]
I always recommend splitting name into First + Last (maybe include middle too, but things get complex w/ intl at that point). Since we are targeting intl users with this, maybe separate it into FamilyName + GivenName

Normally helps with sorting options, and display flexibility. A lot of cases want sorting by family (last) name, sometimes you want `Family, Given` format for display, sometimes you would just want reg. `Given Family` format etc.

Australian homeland security has a good page with specifics on handling foreign names with such a system: https://immi.homeaffairs.gov.au/help-text/eplus/Pages/elp-h0010.aspx#:~:text=Family%20name%20is%20also%20known,an%20individual%20within%20the%20family.

**Comment by hassanhabib** [comment]
> I always recommend splitting name into First + Last (maybe include middle too, but things get complex w/ intl at that point). Since we are targeting intl users with this, maybe separate it into FamilyName + GivenName
> 
> Normally helps with sorting options, and display flexibility. A lot of cases want sorting by family (last) name, sometimes you want `Family, Given` format for display, sometimes you would just want reg. `Given Family` format etc.
> 
> Australian homeland security has a good page with specifics on handling foreign names with such a system: https://immi.homeaffairs.gov.au/help-text/eplus/Pages/elp-h0010.aspx#:~:text=Family%20name%20is%20also%20known,an%20individual%20within%20the%20family.

@AgentEnder good thought - we might need to leave the family name as optional field because I have seen some folk without a last name - but definitely good points.

**Comment by hassanhabib** [comment]
@syedib & @AgentEnder then our model would look something like this:

```csharp
public class User : IAuditable {
    public Guid Id {get; set;}
    public string Name {get; set;}
    public string FamilyName {get; set;}
    public string Email {get; set;}
    public UserStatus Status {get; set;}
    public DateTimeOffset CreatedDate {get; set;}
    public DateTimeOffset UpdatedDate {get; set;}
}


public enum UserStatus {
    Activated,
    Deactivated
}
```

**Comment by AgentEnder** [comment]
@hassanhabib I believe the guidance from Aussie government says to record given name as family name when none is present, though I dont know how I feel about that personally

**Comment by tajwal** [comment]
If this model is going to be used for login and user profile purpose  as well, then I think having below columns will give us plus points.
  -   Unique email can be used for login purpose, in case not then unique  username(Username) is needed.
  -  A column for password(PasswordHash).
  -  In case of storing user image, a column for storing user image path (ProfileImageUrl).
  -  If we wants user to confirm his/her email before using OtripleS, then IsEmailConfirmed column.
  -  If we wants to lock user after certain number of unsuccessful try lock out user account the IsLocked column is needed. 
  -  If we wants to store only one mobile number and do not want to have user contact table them MobileNumber column.
  -  If valid mobile number is required for sending notification purpose then IsMobileNumberConfirmed column.

**Comment by a-urel** [comment]
@hassanhabib why don't we simply use [ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio) and [IdentityServer](https://identityserver.io/)?

**Comment by tajwal** [comment]
> @hassanhabib why don't we simply use [ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio) and [IdentityServer](https://identityserver.io/)?

Mr. @hassanhabib  if you want to use .Net core Identity then better to customize AspNetUser table over their and just add some columns (Name, FamilyName, Status, CreatedDate and ModifiedDate) all other columns exists.

**Comment by HatemGamal** [comment]
A point we should consider which is Students should not create their own users, they only can modify some details, but their user should be created for them by a higher authority user such as students affairs or other, as well as teachers.
In that case we should add 
       ` public Guid CreatedBy { get; set; }`
        `public Guid UpdatedBy { get; set; }`

**Comment by hassanhabib** [comment]
@a-urel & @tajwal  good points.

**Comment by hassanhabib** [comment]
@HatemGamal that would be the system user.

**Comment by hassanhabib** [comment]
This week I am assigning the UserIdentity for user Sign In/ Sign Up to @eriadhami with a deadline of Wed 11:59 PM PST

**Comment by eriadhami** [comment]
@hassanhabib thank you! Just one question, I am going to implement UserIdentity just like other models (Model, Migration, Broker, Service)? No ASP.NET Identity, no implementing IdentityServer4?

**Comment by eriadhami** [comment]
> This week I am assigning the UserIdentity for user Sign In/ Sign Up to @eriadhami with a deadline of Wed 11:59 PM PST

@hassanhabib thank you! Just one question, I am going to implement UserIdentity just like other models (Model, Migration, Broker, Service)? No ASP.NET Identity, no implementing IdentityServer4?

**Comment by hassanhabib** [comment]
@eriadhami  yes it should be exactly the same - I recommend switching the usage of EFxceptions.Identity https://github.com/hassanhabib/EFxceptions/packages/301972 to include UserIdentityContext for your work without losing the benefit of getting meaningful exceptions from EF Core.
