### ISSUE TITLE
Discuss Attendance Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#119]
Hi Everyone,
In this issue, we will discuss the Student Attendance model, here's a draft model:

```csharp
public class Attendance {
    public Guid Id {get; set;}
    public Guid StudentSemesterCourseId {get; set;}
    public DateTimeOffset AttendanceDate {get; set;}
}

```

**Comment by AgentEnder** [comment]
I'd add an enum, AttendanceStatus. Values:

1. Full: Student was present for full class
1. Partial: Student left midway, or was late.
1. Absent: Student was not present.

I do understand that generally the attendance record should not exist if the student was not present on that date, but if the teacher went back and edited the record to state that they were absent, would we want to delete the existing record or just update status?

**Comment by hassanhabib** [comment]
@AgentEnder I love this - good idea!

**Comment by tajwal** [comment]
If students are coming in different times to the school than shift(Id, Name, FromDate, ToDate, StartTime, EndTime, OffDay) table is also required and there will be ShiftId as foreign key in Attendance  table.
adding AttedanceResult, SignInTime and SignOutTime are also good to have in attendance table.
because  AttendanceResult column will tell us that student is Present, late, on-leave or absent, and this result will be calculated base on actual SignInTime and SignOutTime columns which is coming from attendance devices or any third party.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our Attendance entity model and the Attendances this week:

```csharp

using System;

public class Attendance: IAuditable {
    public Guid Id {get; set;}
    public Guid StudentSemesterCourseId {get; set;}
    public AttendanceStatus Status {get; set;}
    public DateTimeOffset AttendanceDate {get; set;}
    public string Notes {get; set;}
    public DateTimeOffset CreatedDate { get; set; }
    public DateTimeOffset UpdatedDate { get; set; }
    public Guid CreatedBy { get; set; }
    public Guid UpdatedBy { get; set; }
}

public enum AttendanceStatus 
{
    Present,
    Partial,
    Absent
}

```
Now, let's talk about Attendances:

## Setup 

- Attendance Model Setup & Migrations with EF Core @HatemGamal Monday 12:00 AM - 11:59 PM PST

## Broker

- Attendance Broker Select By Id function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST
- Attendance Broker Select All function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST
- Attendance Broker Insert function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST
- Attendance Broker Update function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST
- Attendance Broker Delete function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST

## Service

- Attendance Service Add function @hiraldesai by Wednesday 12:00 AM - 11:59 PM PST
- Attendance Service Modify function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
- Attendance Service Retrieve by Id function @viralpandya  by Wednesday 12:00 AM - 11:59 PM PST
- Attendance Service Retrieve All function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
- Attendance Service Delete by Id function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- Attendance Controller Post endpoint @JaAfghan  by Thursday 12:00 AM - 11:59 PM PST
- Attendance Controller Get by Id endpoint @JaAfghan    by Thursday 12:00 AM - 11:59 PM PST
- Attendance Controller Get All endpoint @JaAfghan  by Thursday 12:00 AM - 11:59 PM PST
- Attendance Controller Update endpoint @JaAfghan  by Thursday 12:00 AM - 11:59 PM PST
- Attendance Controller Delete endpoint @JaAfghan  by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- Attendance Post Acceptance Test @Mohamad-ali-8 by Friday 12:00 AM - 11:59 PM PST
- Attendance Update Acceptance Test @Mohamad-ali-8 by Friday 12:00 AM - 11:59 PM PST
- Attendance Get All Acceptance Test @Mohamad-ali-8 by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an Attendance this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by hassanhabib** [comment]
@AgentEnder - reassigning Acceptance Tests to you for this model, let me know if you won't be able to do it.

**Comment by AgentEnder** [comment]
I'll get to it ASAP, might be tomorrow.
