### ISSUE TITLE
Discuss the Exam Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#131]
In this issue we will discuss the Exam model.

here's a draft idea of a model:

```csharp
public class Exam : IAuditable
    {
        public Guid Id { get; set; }
        public string Content { get; set; }

        public Guid SemesterCourseId{ get; set; }
        public SemesterCourse SemesterCourse { get; set; }

        public Guid TeacherId { get; set; }
        public Teacher Teacher { get; set; }

        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }
```

We need to think about the exam content, questions and notes.
There will be additional entities where we attach a student to an exam, or maybe simply through student semester courses - let me know your thoughts.

**Comment by a-urel** [comment]
- Exam type (eg. 1st "Exam", "2nd Exam", "Term Paper"...)
- Exam status (eg. Draft, Completed, Canceled)

**Comment by AgentEnder** [comment]
Huh, I meant to leave this comment ~2 days ago but must have never submitted it.

This entity seems like it should have a relation to assignment. Something like all exams are assignments, not all assignments are exams. Perhaps a nullable foreign key ExamId on the assignments model.

@a-urel  I agree completely with status, although I would prefer closed to completed. Completed sounds like something the student does, and makes more sense on a related entity like StudentExam (or perhaps through the relation to assignment, and StudentAssignment if the previous suggestion is taken).

**Comment by a-urel** [comment]
@AgentEnder @hassanhabib I found a grade calculator:

![image](https://user-images.githubusercontent.com/66084385/91559266-6e8af280-e940-11ea-85df-5eb0941dc246.png)

Maybe a single **Assignment/Exam** entity is better design.

**Comment by AgentEnder** [comment]
I think it definitely would be a better model to have one assignment entity, and just use the name / description and weight to indicate an exam.

**Comment by eriadhami** [comment]
> I think it definitely would be a better model to have one assignment entity, and just use the name / description and weight to indicate an exam.

Totally agree. Maybe we have to add also AssignmentType on Assignment model eg. Homework, Project, Midterm, Final

**Comment by AgentEnder** [comment]
If we had an entity SemesterCourseAssignmentType teachers would be able to create assignment types and adjust their weights independently for each semester

**Comment by a-urel** [comment]
So this issue can be closed. We can create a new issue to modify `Assignment` entity to support both assignments and exams.

**Comment by hassanhabib** [comment]
@a-urel I think assignments are more common to be distinct from exams right?

**Comment by hassanhabib** [comment]
Let's have the only task for this week to add a type for assignments to either be: `Homework`, `Lab`, `Quiz`, `Project` and Exam - I will assign the task to @a-urel

**Comment by AgentEnder** [comment]
@hassanhabib if we want to support in application tests/quizzes/whatever we will need a basic form builder.

I feel like this is the route you were going with the exams. In which case you would have entities like:

Exam {
    Exam Id : Guid
    SemesterCourseId: guid
    Name : string
    Published : boolean
    Allowed Attempts: int
    Grading Method: enum [newest, average]

}

Exam Question {
    Exam Question Id:  guid
    ExamId : guid
    QuestionText : string
    QuestionType: enum [multiple choice, fill in the blank, short answer, file attachment]
}

Exam Question Choices {
    ExamQuestionChoiceId : guid
    ExamQuestionId: Guid
    ChoiceText: guid
    Correct : boolean
}

Student Exam{
    StudentId: guid
    ExamId: guid
    StartedAt: datetime
    CompletedAt: datetime
    Attempts: int
    Score: float
    RawData: json
}

StudentExamAttachment { (used for file attachment questions )
    StudentId: guid
    ExamQuestionId : guid
    Bytes or storage location 
}

I still feel like exam might be a misnomer, quiz might fit better. Either way, I think this is closer to the intent.

**Comment by a-urel** [comment]
@AgentEnder I think _creating exam contents and supporting in-app exams_ is a different business requirement. 
This can even be even a different product. 
I admit creating form and content builders in the future would be fun though.

**Comment by hassanhabib** [comment]
@a-urel sounds good to me, do you want to take this task?

**Comment by a-urel** [comment]
@hassanhabib yes, I'm working on the `Assignment` entity now.

**Comment by a-urel** [comment]
I think these models meet the requirements:

```csharp
    /// <summary>
    /// Abstract base class for Assignment-Templates and Course-Assignments
    /// </summary>
    public abstract class Assignment : IAuditable
    {
        public Guid Id { get; set; }

        /// <summary>
        /// 1st Exam, Homework, Project, Term-Paper, etc.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// > 0 : Affects final grade
        /// = 0 : Doesn't affect final grade
        /// </summary>
        public int Weight { get; set; }

        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }
```
```csharp
    /// <summary>
    /// Assignment-Template to be copied to Course-Assignments
    /// </summary>
    public class AssignmentTemplate : Assignment
    {
        public bool Archived { get; set; }
    }
```
```csharp
    /// <summary>
    /// Course-Assignment
    /// </summary>
    public class CourseAssignment : Assignment
    {
        public string Description { get; set; }

        public SemesterCourse SemesterCourse { get; set; }

        public AssignmentStatus AssignmentStatus { get; set; }

        /// <summary>
        /// Date or Deadline
        /// </summary>
        public DateTimeOffset DateTime { get; set; }

        /// <summary>
        /// A classroom can be assigned for an exam
        /// </summary>
        public Classroom Classroom { get; set; }

        /// <summary>
        /// Calculated average grade for this assignment
        /// if Weight > 0
        /// </summary>
        public int? AverageGrade { get; set; }
    }
```

What do you think?

**Comment by AgentEnder** [comment]
@a-urel I dont think the form building capabilities should be relegated to a different product. Looking at other technologies in use in classrooms (canvas or blackboard being the 2 I have personal experience with), most of my assignments posted through the systems were built using the software.

If we want this software to be used, and truly eliminate the costs to schools this should be a firm requirement. 

What do you think @hassanhabib

**Comment by hassanhabib** [comment]
@a-urel the rule with 0s affecting final grades are not self-explanatory.
I would go with something like a status for grade impact.

@AgentEnder I agree 100% - the whole idea is to simplify and invent an easier way to do schooling systems - not another product like the existing ones, absolutely.

@a-urel can we simplify things a bit from a model design perspective?

**Comment by a-urel** [comment]
@hassanhabib @AgentEnder I think we should clarify the definition of our product. 

I thought OtripleS as a [school information system](https://en.wikipedia.org/wiki/Student_information_system) for [K12](https://en.wikipedia.org/wiki/K%E2%80%9312), not a [learning management system](https://en.wikipedia.org/wiki/Learning_management_system). 

We can aim to provide both functionality, of course. But even in this case, we can't force our users to use in-app exams. Some of them may prefer to use paper exams and enter only grades. IMO we should design _learning management system module(s)_ separately, if we will add this functionality.

**Comment by hassanhabib** [comment]
@a-urel it's definitely not a learning management system (yet) - I agree with you, it should just be for schools to be able to manage their students data.
But ideally we will have an extension OtripleS.Learn where we integrate with Microsoft Teams for instance to provide a seamless classroom experience, since this is where it seems things are going since the pandemic.

**Comment by a-urel** [comment]
This is the modified `Assignment` model:

```csharp
    /// <summary>
    /// Abstract base class for Assignment-Templates and Course-Assignments
    /// </summary>
    public abstract class Assignment : IAuditable
    {
        public Guid Id { get; set; }

        /// <summary>
        /// 1st Exam, Homework, Project, Term-Paper, etc.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// I couldn't find a better name
        /// </summary>
        public bool CanBeGraded { get; set; }

        public bool AffectsFinalGrade { get; set; }

        public int Weight { get; set; }

        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }
```

**Comment by hassanhabib** [comment]
@a-urel LGTM, go for it.
