### ISSUE TITLE
Discuss Guardian Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#144]
Hi everyone,
Let's start thinking about the guardian entity model, a guardian for a student can be their parents, grandparents older siblings or other here's a basic model for discussion:

```csharp 

public class Guardian : IAuditable {

    public Guid Id {get; set;}
    public string FirstName {get; set;}
    public string FamilyName {get; set;}
    public GuardianRelationship Relationship {get; set;}
    public DateTimeOffset CreatedDate {get; set;}
    public DateTimeOffset UpdatedDate {get; set;}
    public Guid CreatedBy {get; set;}
    public Guid UpdatedBy {get; set;}
}


public enum GuardianRelationship {
    Parent,
    Sibling,
    Family,
    Other
}

```

**Comment by AgentEnder** [comment]
This would need either a StudentId (in case of 1 to many) or a join table to relate back to students.

Might want to have a flag describing if its the primary contact. Contact info would also make sense. Probably home phone, cell phone, and email at minimum. Contact info could also be normalized into its own table, but thats probably not necessary.

**Comment by hassanhabib** [comment]
@AgentEnder I agree, a glue entity to attach the guardian to the student with a description of the relationship - great point.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our Guardian entity model and the Guardians this week:

```csharp

public class Guardian : IAuditable {

    public Guid Id {get; set;}
    public string FirstName {get; set;}
    public string FamilyName {get; set;}
    public DateTimeOffset CreatedDate {get; set;}
    public DateTimeOffset UpdatedDate {get; set;}
    public Guid CreatedBy {get; set;}
    public Guid UpdatedBy {get; set;}
}

```
Now, let's talk about Guardians:

## Setup 

- Guardian Model Setup & Migrations with EF Core @JaAfghan  Monday 12:00 AM - 11:59 PM PST

## Broker

- Guardian Broker Select By Id function @JaAfghan  by Tuesday 12:00 AM - 11:59 PM PST
- Guardian Broker Select All function @JaAfghan  by Tuesday 12:00 AM - 11:59 PM PST
- Guardian Broker Insert function @JaAfghan  by Tuesday 12:00 AM - 11:59 PM PST
- Guardian Broker Update function @JaAfghan  by Tuesday 12:00 AM - 11:59 PM PST
- Guardian Broker Delete function @JaAfghan  by Tuesday 12:00 AM - 11:59 PM PST

## Service

- Guardian Service Add function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- Guardian Service Modify function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
- Guardian Service Retrieve by Id function @AgentEnder  by Wednesday 12:00 AM - 11:59 PM PST
- Guardian Service Retrieve All function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- Guardian Service Delete by Id function @hiraldesai  by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- Guardian Controller Post endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST
- Guardian Controller Get by Id endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST
- Guardian Controller Get All endpoint @tajwal  by Thursday 12:00 AM - 11:59 PM PST
- Guardian Controller Update endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST
- Guardian Controller Delete endpoint @tajwal   by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- Guardian Post Acceptance Test @Akinnagbe by Friday 12:00 AM - 11:59 PM PST
- Guardian Update Acceptance Test @Akinnagbe by Friday 12:00 AM - 11:59 PM PST
- Guardian Get All Acceptance Test @Akinnagbe by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an Guardian this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by AgentEnder** [comment]
If anyone wants to take my service task this go around I'd appreciate it. My dev machine started overheating over the weekend and I'm unfortunately not going to get it back in time to work on this today. @hassanhabib  (@eriadhami this one is pretty similar to yours, might be easy to knock out both).

Sorry.

**Comment by eriadhami** [comment]
> If anyone wants to take my service task this go around I'd appreciate it. My dev machine started overheating over the weekend and I'm unfortunately not going to get it back in time to work on this today. @hassanhabib  (@eriadhami this one is pretty similar to yours, might be easy to knock out both).
> 
> 
> 
> Sorry.

Sure, i can do that

**Comment by AgentEnder** [comment]
Appreciate it @eriadhami , I've kept personal projects off work computer so far and I'd like to keep it that way.
