### ISSUE TITLE
Discuss Student Guardian Relationship Entity

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#146]
Hi Everyone,
This is the relationship entity between students and guardians, here's a draft model:

```csharp
    public class StudentGuardian : IAuditable
    {
        public Guid GuardianId { get; set; }
        public Guid StudentId { get; set; }
        public GuardianStudentRelationship Relationship{ get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }

    public enum GuardianStudentRelationship
    {
        Parent,
        Family,
        Other
    }
```

This will be a composite primary key case, here's an example of how that was done here: https://github.com/hassanhabib/OtripleS/blob/9ef94d0b9abb00fe5cc5de614b506c8077d93204/OtripleS.Web.Api/Brokers/Storage/StorageBroker.StudentSemesterCourses.References.cs#L14-L17

**Comment by AgentEnder** [comment]
I'd want a bit flag called PrimaryContact or something like that. Where are we storing the actual contact info for guardians?

**Comment by hassanhabib** [comment]
> I'd want a bit flag called PrimaryContact or something like that. Where are we storing the actual contact info for guardians?

In a separate Contact table

**Comment by AgentEnder** [comment]
That makes sense, was not sure how normalized we would keep that. I've seen systems that do both. The PrimaryContact, or maybe even PrimaryGuardian flag still makes sense imho.

**Comment by hassanhabib** [comment]
> That makes sense, was not sure how normalized we would keep that. I've seen systems that do both. The PrimaryContact, or maybe even PrimaryGuardian flag still makes sense imho.

Definitely, I agree.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our StudentGuardian entity model this week:

```csharp

public class StudentGuardian : IAuditable
    {
        public Guid GuardianId { get; set; }
        public Guid StudentId { get; set; }
        public GuardianStudentRelationship Relationship { get; set; }
        public bool IsPrimaryContact {get; set;}
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }

    public enum GuardianStudentRelationship
    {
        Parent,
        Family,
        Other
    }

```
Now, let's talk about StudentGuardians:

## Setup 

- StudentGuardian Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST

## Broker

- StudentGuardian Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- StudentGuardian Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- StudentGuardian Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- StudentGuardian Broker Update function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- StudentGuardian Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST

## Service

- StudentGuardian Service Add function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- StudentGuardian Service Modify function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
- StudentGuardian Service Retrieve by Id function @AgentEnder  by Wednesday 12:00 AM - 11:59 PM PST
- StudentGuardian Service Retrieve All function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- StudentGuardian Service Delete by Id function @JaAfghan by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- StudentGuardian Controller Post endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentGuardian Controller Get by Id endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentGuardian Controller Get All endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentGuardian Controller Update endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentGuardian Controller Delete endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- StudentGuardian Post Acceptance Test @tobidub by Friday 12:00 AM - 11:59 PM PST
- StudentGuardian Update Acceptance Test @tobidub by Friday 12:00 AM - 11:59 PM PST
- StudentGuardian Get All Acceptance Test @tobidub by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an StudentGuardian this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by devmanzur** [comment]
I am really sorry to let you know i will not be able to complete this weeks task because i am in a remote location, i did not expect the internet to be this bad here. Extremely sorry. Can someone complete my task please?

**Comment by viralpandya** [comment]
@devmanzur : I can take up your task.
