### ISSUE TITLE
Discuss Contact Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#158]
Hi everyone,
In this issue, we want to discuss a contact model, a contact model could be for student, teacher, admin, guardian or any other person entity on the system, here's a draft:

```csharp
public class Contact: IAuditable
    {
        public Guid Id { get; set; }
        public bool IsPrimary {get; set;}
        public ContactType Type {get; set;}
        public string Information {get; set;}
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }

public enum ContactType {
    Email,
    Phone,
    Other
}
```

**Comment by AgentEnder** [comment]
Phone should be split into at least Cellphone and reg. Phone, maybe work phone too. Knowing that a number is textable would be important.

**Comment by devmanzur** [comment]
Hello @hassanhabib sorry for being inactive while. Can I start contributing from this week?

**Comment by hassanhabib** [comment]
> Phone should be split into at least Cellphone and reg. Phone, maybe work phone too. Knowing that a number is textable would be important.

@AgentEnder good point, yes.

**Comment by hassanhabib** [comment]
> > Phone should be split into at least Cellphone and reg. Phone, maybe work phone too. Knowing that a number is textable would be important.
> 
> @AgentEnder good point, yes.

@devmanzur you sure can, will assign some work to you tonight.

**Comment by hassanhabib** [comment]
> Hello @hassanhabib sorry for being inactive while. Can I start contributing from this week?

@devmanzur you sure can, will assign some work to you tonight.

**Comment by devmanzur** [comment]
> > Hello @hassanhabib sorry for being inactive while. Can I start contributing from this week?
> 
> @devmanzur you sure can, will assign some work to you tonight.

Thank you

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our Contact entity model this week:

```csharp
public class Contact: IAuditable
    {
        public Guid Id { get; set; }
        public bool IsPrimary {get; set;}
        public ContactType Type {get; set;}
        public string Information {get; set;}
        public string Notes {get; set;}
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }

public enum ContactType {
    Email,
    Phone,
    Other
}
```
Now, let's talk about Contacts:

## Setup 

- Contact Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST [done]

## Broker

- Contact Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- Contact Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- Contact Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- Contact Broker Update function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- Contact Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]

## Service

- Contact Service Add function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- Contact Service Modify function @tobidub by Wednesday 12:00 AM - 11:59 PM PST [done *]
- Contact Service Retrieve by Id function @AgentEnder  by Wednesday 12:00 AM - 11:59 PM PST
- Contact Service Retrieve All function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- Contact Service Delete by Id function @JaAfghan by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- Contact Controller Post endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST
- Contact Controller Get by Id endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST
- Contact Controller Get All endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST
- Contact Controller Update endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST
- Contact Controller Delete endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- Contact Post Acceptance Test @MChorfa  by Friday 12:00 AM - 11:59 PM PST
- Contact Update Acceptance Test @MChorfa  by Friday 12:00 AM - 11:59 PM PST
- Contact Get All Acceptance Test @MChorfa  by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an Contact this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by AgentEnder** [comment]
@hassanhabib are we not going to differentiate cell phones as discussed? This is fine if we don't want to, but school admins might want to send a text via some service such as remind.com that would only be effective for cells

**Comment by hassanhabib** [comment]
> @hassanhabib are we not going to differentiate cell phones as discussed? This is fine if we don't want to, but school admins might want to send a text via some service such as remind.com that would only be effective for cells

@AgentEnder Definitely, go ahead and add an enum for `CellPhone` in the options.

**Comment by hassanhabib** [comment]
@tobidub if you have the capacity, please take care of the acceptance tests for `Contacts`

**Comment by devmanzur** [comment]
> @tobidub if you have the capacity, please take care of the acceptance tests for `Contacts`

I can take that.

**Comment by tobidub** [comment]
> > @tobidub if you have the capacity, please take care of the acceptance tests for `Contacts`
> 
> I can take that.

Sure give it a try :) If you have problems, i will do it in the evening.

**Comment by devmanzur** [comment]
done
