### ISSUE TITLE
Student Contact

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#176]
This upcoming sprint we will be discussing attaching contact entities to a student entity.
Ideally, a contact entity and a student entity should have a middle entity in between to allow the following:
1. Having multiple contacts for one student.
2. younger students with the same contact information (usually it's just the parents phones).
So this is very likely a many-to-many relationship.
by the time this Sprint is over, I would have successfully upgraded to .NET 5 RC, which comes with EF 5 that offers an out of box many-to-many relationship builder without needing to design a glue entity, check some more information here:
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many

We might not necessarily need that for our business case here, but it's definitely something to consider.
Traditionally, a glue entity would look something like this:

```csharp
public class StudentContact {
    public Guid contactId {get; set;}
    public Guid studentId {get; set;}
}

```

Let's discuss.

**Comment by AgentEnder** [comment]
I think a glue entity would be suited.

Use case: brother + half sister.

Brother has mom + dad as contacts, dad as primary contact. Half sister may still have mom as a contact, but her primary contact might be her dad. Glue entity would prevent duplication of the mom record. Glue entity also allows having the bit field for IsPrimary

**Comment by tobidub** [comment]
I dont think students should share contacts.

And we already have a primary field in contacts.

**Comment by AgentEnder** [comment]
@tobidub my proposal would be moving the primary field from contact to the glue entity. 

How would you propose storing contacts for brother + sister? Without them sharing contacts you would be duplicating data. Updating the phone number would have to be done for each sibling

**Comment by tobidub** [comment]
Shouldnt they then share the same guardian? and the guardian has a contact with those information.

Student Contact is for me Student specific.

**Comment by AgentEnder** [comment]
@tobidub You are 100% correct, I dont know where my head was at. For some reason I was combining this with studentguardian entity. My bad.

**Comment by tobidub** [comment]
@AgentEnder no problem. This is a discussion, so we have to discuss ;)

**Comment by a-urel** [comment]
Though students might share contacts, Joe's mother might be Jane's aunt. 
So, one-to-many relationship between `Student` and `Contact` would be better, IMO.

**Comment by AgentEnder** [comment]
@a-urel I think you're making the same mistake I was making. This entity would be to store the student's own contact info, not their guardians or relatives. StudentGuardianContact would be a different entity relating StudentGuardian to a Contact record.

**Comment by a-urel** [comment]
Well, no idea then :)

**Comment by hassanhabib** [comment]
@AgentEnder what if the student has multiple contact options? maybe they have two phones? or even multiple contacts of different types?
Now, for students sharing contacts, it doesn't necessarily have to be through the guardian, but I can see this situation being less and less likely to happen today.
Back in the day, there used to be one landline phone for the entire family, so my contact is my brother's contact and so on for the rest of the family.
I don't know if this situation might be viable today. but considering the fact that we want this system to be universal, to reach everywhere to help everyone, I suggest we allow having students sharing the same contact as it doesn't really harm the system in any way, this falls under the category of information, the more you have of it, the more diverse it is, the easier we allow people to enter their information or use existing ones the better.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our StudentContact entity model this week:

```csharp
public class StudentContact {
    public Guid StudentContactId {get; set;}
    public Guid studentId {get; set;}
}
```
Now, let's talk about StudentContacts:

## Setup 

- StudentContact Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST [done]

## Broker

- StudentContact Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- StudentContact Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- StudentContact Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- StudentContact Broker Update function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- StudentContact Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]

## Service

- StudentContact Service Add function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
- StudentContact Service Modify function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST [done *]
- StudentContact Service Retrieve by Id function @AgentEnder  by Wednesday 12:00 AM - 11:59 PM PST
- StudentContact Service Retrieve All function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- StudentContact Service Delete by Id function @a-urel by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- StudentContact Controller Post endpoint @devmanzur  by Thursday 12:00 AM - 11:59 PM PST
- StudentContact Controller Get by Id endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST
- StudentContact Controller Get All endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST
- StudentContact Controller Update endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST
- StudentContact Controller Delete endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- StudentContact Post Acceptance Test @JaAfghan by Friday 12:00 AM - 11:59 PM PST
- StudentContact Update Acceptance Test @HatemGamal  by Friday 12:00 AM - 11:59 PM PST
- StudentContact Get All Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an StudentContact this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by eriadhami** [comment]
> Thank you all for your contributions, here's an overview of our StudentContact entity model this week:
> 
> 
> 
> ```csharp
> 
> public class StudentContact {
> 
>     public Guid StudentContactId {get; set;}
> 
>     public Guid studentId {get; set;}
> 
> }
> 
> ```
> 
> Now, let's talk about StudentContacts:
> 
> 
> 
> ## Setup 
> 
> 
> 
> - StudentContact Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST [done @eriadhami ]
> 
> 
> 
> ## Broker
> 
> 
> 
> - StudentContact Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done @eriadhami ]
> 
> - StudentContact Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done @eriadhami ]
> 
> - StudentContact Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done @eriadhami ]
> 
> - StudentContact Broker Update function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done @eriadhami ]
> 
> - StudentContact Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done @eriadhami ]
> 
> 
> 
> ## Service
> 
> 
> 
> - StudentContact Service Add function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Service Modify function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST 
> 
> - StudentContact Service Retrieve by Id function @AgentEnder  by Wednesday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Service Retrieve All function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Service Delete by Id function @a-urel by Wednesday 12:00 AM - 11:59 PM PST
> 
> 
> 
> ## Controller
> 
> 
> 
> - StudentContact Controller Post endpoint @devmanzur  by Thursday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Controller Get by Id endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Controller Get All endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Controller Update endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Controller Delete endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST
> 
> 
> 
> 
> 
> ## Acceptance Tests
> 
> 
> 
> - StudentContact Post Acceptance Test @JaAfghan by Friday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Update Acceptance Test @HatemGamal  by Friday 12:00 AM - 11:59 PM PST
> 
> - StudentContact Get All Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST
> 
> 
> 
> 
> 
> ## Contribution Rules:
> 
> 1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
> 
> 2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
> 
> 3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
> 
> 4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.
> 
> 
> 
> If you haven't had an StudentContact this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.
> 
> 
> 
> As soon as all these tasks are done, this issue will be closed.
> 
> 
> 
> Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.
> 
> 

If anyone needs help with the tasks I would be happy to help.

**Comment by AgentEnder** [comment]
@eriadhami I've been caught up between work and working on buying a house, if you could take a look at mine I'd appreciate it as its already overdue

**Comment by eriadhami** [comment]
> @eriadhami I've been caught up between work and working on buying a house, if you could take a look at mine I'd appreciate it as its already overdue

@AgentEnder don't worry my friend. I will finish it later.

**Comment by viralpandya** [comment]
I am working on my task.

**Comment by devmanzur** [comment]
working on my task

**Comment by devmanzur** [comment]
anyone else facing this issue? 
[https://photos.app.goo.gl/4o3vqwvx8iQ8N3f66](url)

**Comment by devmanzur** [comment]
anyone else facing this issue? 
[](https://photos.app.goo.gl/4o3vqwvx8iQ8N3f66)

**Comment by devmanzur** [comment]
anyone else facing this issue? https://photos.app.goo.gl/4o3vqwvx8iQ8N3f66

**Comment by a-urel** [comment]
I've just started my task, sorry for delay.

**Comment by devmanzur** [comment]
Build failed:

`  OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1)
  OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.Tools 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.Tools 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1)
  OtripleS.Web.Api.csproj: [NU1202] Package RESTFulSense 1.6.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package RESTFulSense 1.6.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)
  OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.Design 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.Design 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1)`

Anyone else having this issue?

**Comment by hassanhabib** [comment]
> Build failed:
> 
> ` OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1) OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.Tools 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.Tools 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1) OtripleS.Web.Api.csproj: [NU1202] Package RESTFulSense 1.6.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package RESTFulSense 1.6.0 supports: netstandard2.1 (.NETStandard,Version=v2.1) OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.Design 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.Design 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1)`
> 
> Anyone else having this issue?

@devmanzur did you follow the steps I pointed out in here?
https://www.youtube.com/watch?v=ufjtuAel538&ab_channel=HassanHabib

**Comment by devmanzur** [comment]
> > Build failed:
> > ` OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1) OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.Tools 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.Tools 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1) OtripleS.Web.Api.csproj: [NU1202] Package RESTFulSense 1.6.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package RESTFulSense 1.6.0 supports: netstandard2.1 (.NETStandard,Version=v2.1) OtripleS.Web.Api.csproj: [NU1202] Package Microsoft.EntityFrameworkCore.Design 5.0.0-rc.1.20451.13 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.EntityFrameworkCore.Design 5.0.0-rc.1.20451.13 supports: netstandard2.1 (.NETStandard,Version=v2.1)`
> > Anyone else having this issue?
> 
> @devmanzur did you follow the steps I pointed out in here?
> https://www.youtube.com/watch?v=ufjtuAel538&ab_channel=HassanHabib

I missed it, my bad

**Comment by viralpandya** [comment]
Hi OTripleS Team,

Thank you for all the good work. Keep working and keep growing. 

Some team members were running late for their tasks. I was assigned modify task and glue entity does not require modify. So, I have worked on delete task after talking to @hassanhabib . 

Sorry @a-urel , if I have completed your task and if you were working on the same. 

@Team: Please feel free to ask for help, if anyone is juggling with their resources.

Regards,
Viral
