### ISSUE TITLE
Teacher Contact

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#178]
This issue should be just like a teacher contact
```csharp
public class TeacherContact {
    public Guid ContactId {get; set;}
    public Guid TeacherId {get; set;}
}
```

The case for many to many here is just simply teachers sharing the same office with the same landline phone number as an option of contact - let's discuss.

**Comment by a-urel** [comment]
@hassanhabib Probably, many-to-many relation between a person and his/her contact info is an over-engineered approach. Let's use a simpler design. People usually don't have common phone numbers, e-mail addresses, etc.

**Comment by hassanhabib** [comment]
> @hassanhabib Probably, many-to-many relation between a person and his/her contact info is an over-engineered approach. Let's use a simpler design. People usually don't have common phone numbers, e-mail addresses, etc.

@a-urel they usually don't - but sometimes they do - we should be able to cover that edge case if we need to especially that the cost isn't that high to have that model.

**Comment by AgentEnder** [comment]
If we do many-to-many here than the IsPrimary field definitely needs to be remembered. Otherwise, I see no problems with either approach and the added flexibility may be worth it.

**Comment by hassanhabib** [comment]
Will post the tasks/assignments for this tonight, thanks.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our TeacherContact entity model this week:

```csharp
public class TeacherContact {
    public Guid TeacherContactId {get; set;}
    public Guid TeacherId {get; set;}
}
```
Now, let's talk about TeacherContacts:

## Setup 

- TeacherContact Model Setup & Migrations with EF Core @viralpandya  Monday 12:00 AM - 11:59 PM PST

## Broker

- TeacherContact Broker Select By Id function @viralpandya  by Tuesday 12:00 AM - 11:59 PM PST
- TeacherContact Broker Select All function @viralpandya  by Tuesday 12:00 AM - 11:59 PM PST
- TeacherContact Broker Insert function @viralpandya  by Tuesday 12:00 AM - 11:59 PM PST
- TeacherContact Broker Update function @viralpandya  by Tuesday 12:00 AM - 11:59 PM PST
- TeacherContact Broker Delete function @viralpandya  by Tuesday 12:00 AM - 11:59 PM PST

## Service

- TeacherContact Service Add function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
- TeacherContact Service Retrieve by Id function @AgentEnder  by Wednesday 12:00 AM - 11:59 PM PST
- TeacherContact Service Retrieve All function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- TeacherContact Service Delete by Id function @viralpandya   by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- TeacherContact Controller Post endpoint @tobidub   by Thursday 12:00 AM - 11:59 PM PST
- TeacherContact Controller Get by Id endpoint @tobidub  by Thursday 12:00 AM - 11:59 PM PST
- TeacherContact Controller Get All endpoint @tobidub  by Thursday 12:00 AM - 11:59 PM PST
- TeacherContact Controller Update endpoint @tobidub  by Thursday 12:00 AM - 11:59 PM PST
- TeacherContact Controller Delete endpoint @tobidub  by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- TeacherContact Post Acceptance Test @hassanhabib by Friday 12:00 AM - 11:59 PM PST
- TeacherContact Update Acceptance Test @hassanhabib   by Friday 12:00 AM - 11:59 PM PST
- TeacherContact Get All Acceptance Test @hassanhabib  by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an TeacherContact this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.
