### ISSUE TITLE
CODE RUB: SEPRATE LOGIC TESTS FOR EACH OPERATION - Attachments

### ISSUE THREAD

**Issue by Mehdi-Aghaei** [hassanhabib/OtripleS#1816]

**Comment by imjane5** [comment]
Please assign to @imjane5.

**Comment by ShriHumrudha** [comment]
@Noahmahi2019 is assigned here.

Rename the below file to 'AttachmentServiceTests.Logic.RetrieveAll.cs'
![image](https://user-images.githubusercontent.com/89320816/167203301-d667df86-a429-4a3d-808f-faf66984a35c.png)

**Comment by glhays** [comment]
As compleyed
