### ISSUE TITLE
Guardian Contact

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#183]
Just as we did with students and teachers, let's discuss the Guardian Contact

```csharp
public class GuardianContact {
    public Guid GuardianContactId {get; set;}
    public Guid GuardianId {get; set;}
}
```

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our GuardianContact entity model this week:

```csharp
public class GuardianContact {
    public Guid ContactId {get; set;}
    public Guid GuardianId {get; set;}
}
```
Now, let's talk about GuardianContacts:

## Setup 

- GuardianContact Model Setup & Migrations with EF Core @Jamaxack  Monday 12:00 AM - 11:59 PM PST

## Broker

- GuardianContact Broker Select By Id function @Jamaxack  by Tuesday 12:00 AM - 11:59 PM PST
- GuardianContact Broker Select All function @Jamaxack  by Tuesday 12:00 AM - 11:59 PM PST
- GuardianContact Broker Insert function @Jamaxack  by Tuesday 12:00 AM - 11:59 PM PST
- GuardianContact Broker Delete function @Jamaxack  by Tuesday 12:00 AM - 11:59 PM PST

## Service

- GuardianContact Service Add function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- GuardianContact Service Retrieve by Id function @eriadhami  by Wednesday 12:00 AM - 11:59 PM PST
- GuardianContact Service Retrieve All function @AgentEnder by Wednesday 12:00 AM - 11:59 PM PST
- GuardianContact Service Delete by Id function @tobidub by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- GuardianContact Controller Post endpoint @tobidub   by Thursday 12:00 AM - 11:59 PM PST
- GuardianContact Controller Get by Id endpoint @tobidub  by Thursday 12:00 AM - 11:59 PM PST
- GuardianContact Controller Get All endpoint @tobidub  by Thursday 12:00 AM - 11:59 PM PST
- GuardianContact Controller Delete endpoint @tobidub  by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- GuardianContact Post Acceptance Test @hassanhabib by Friday 12:00 AM - 11:59 PM PST
- GuardianContact Update Acceptance Test @hassanhabib   by Friday 12:00 AM - 11:59 PM PST
- GuardianContact Get All Acceptance Test @hassanhabib  by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an GuardianContact this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by eriadhami** [comment]
> ## Setup 
> 
> - GuardianContact Model Setup & Migrations with EF Core @Jamaxack  Monday 12:00 AM - 11:59 PM PST
> 
> ## Broker
> 
> - GuardianContact Broker Select By Id function @Jamaxack  by Tuesday 12:00 AM - 11:59 PM PST
> - GuardianContact Broker Select All function @Jamaxack  by Tuesday 12:00 AM - 11:59 PM PST
> - GuardianContact Broker Insert function @Jamaxack  by Tuesday 12:00 AM - 11:59 PM PST
> - GuardianContact Broker Delete function @Jamaxack  by Tuesday 12:00 AM - 11:59 PM PST
> 

@Jamaxack, if you need help with your task I will be happy to help.
