### ISSUE TITLE
CODE RUB: Rule & Parameter Should Be @ The Same Level

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#1968]
https://github.com/hassanhabib/OtripleS/blob/c259316151682656a16e657368d83dd3d122ba15/OtripleS.Web.Api/Services/Foundations/Students/StudentService.Validations.cs#L33

@moisesjgomez

**Comment by ShriHumrudha** [comment]
@moisesjgomez please confirm if this is resolved.

**Comment by ShriHumrudha** [comment]
@Noahmahi2019 is assigned here
