### ISSUE TITLE
CODE RUB: Replace `== null` with `is null`

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#1973]
https://github.com/hassanhabib/OtripleS/blob/1ccf37af07278b4b1f65e6c4dcdb1f9a3c037039/OtripleS.Web.Api/Services/Foundations/Registrations/RegistrationService.Validations.cs#L213

Assigned to @hoxhaleo319

**Comment by hoxhaleo319** [comment]
@hassanhabib this is already completed by someone else before I got to it.
