### ISSUE TITLE
CODE RUB: Reaplce `default` with Guids to `Guid.Empty`

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#1995]
https://github.com/hassanhabib/OtripleS/blob/71326397e4ecd14daee12a658f2ce1a50bcc0895/OtripleS.Web.Api/Services/Foundations/StudentGuardians/StudentGuardianService.Validations.cs#L70

Assigned to: @nedataghiparast

**Comment by nedataghiparast** [comment]
I completed the task.
