### ISSUE TITLE
> FatherName,Fathers email and mobile and gender of student.

### ISSUE THREAD

**Issue by tajwal** [hassanhabib/OtripleS#2]
> FatherName,Fathers email and mobile and gender of student.

@tajwal I wonder if these values should be in a different related entity, not directly in the main student entity.

_Originally posted by @hassanhabib in https://github.com/hassanhabib/OtripleS/issues/1#issuecomment-647358292_

**Comment by devmanzur** [comment]
This seems to be unintentional, please refer to the original issue. Thanks
