### ISSUE TITLE
Discuss Exam Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#209]
In this cycle of features we will be working on the following entities:
Exams
Student Exam
Student Grades (Reports)
Calendar
Attachments 
There might be some other entities related we will discuss as we go.

```csharp
public class Exam {
   public Guid Id {get; set;}
   public Guid SemesterId {get; set;}
   public Guid CourseId {get; set;}
   public string Label {get; set;}
   ... Audit Fields 
}

```

Let's discuss.

**Comment by AgentEnder** [comment]
Should this model also include necessary entities to handle form creation / web-based exams in addition to paper based?

Web based being exams that OTripleS displays and students take within our web client, Paper based being anything else, where OTripleS functions as a web based grade book?

**Comment by hassanhabib** [comment]
@AgentEnder that's a good point - and yes we should add to this model references to all related entities (as soon as they are created) I am still thinking however about the relationships between an exam and a student - we might need an `StudentExam` glue entity to handle that situation.
There are situations where students may need to retry and take the exam again, but in that case that would be a completely new record of `Exam` to prevent repetitive questions.

**Comment by AgentEnder** [comment]
I think a StudentExam entity does make sense, having properties:
```csharp
public class StudentExam {
    public Guid StudentId {get;set;}
    public Guid ExamId {get;set;}
    public byte Attempts {get;set;}
}
```

As far as using a new Exam record for retaking exams, I would not agree with that. There are situations where a teacher may want a student to take the same version of the exam, and even if that is not the case then there would still need to be a relationship between the original exam and the second attempt's exam. I'd propose something like an ExamVersion entity.

**Comment by tobidub** [comment]
I dont know if im getting this right.

There is an Exam about a Topic of Course in one Semester. (i dont lets say CourseExam)

A Teacher can create different Exams about a Topic of a Course. (TeacherCourseExam)
(Will there be a relationship between Teacher and Course)


A Student can take Exams created by a Teacher about a Topic multiple times
And an Other Student can take the same Exam

**Comment by tobidub** [comment]
There is a Exam about a Topic of Course
There is the concrete Exam created by a Teacher about a Topic of Course
There is a Exam about a Topic of Course created by a Teacher that a Student took which can be graded

Which Exam are we trying to model here?

**Comment by hassanhabib** [comment]
@tobidub graded exams precisely - mid-terms, finals .. etc.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our UserContact entity model this week:

```csharp
    public class Exam : IAuditable
    {
        public Guid Id { get; set; }
        public string Label { get; set; }
        public string Content { get; set; }
        public string Notes { get; set; }
        public ExamType Type { get; set; }

        public Guid SemesterCourseId { get; set; }
        public SemesterCourse SemesterCourse { get; set; }

        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }

    public enum ExamType
    {
        Quiz,
        MidTerm,
        Final,
        Other
    }
```
Now, let's talk about UserContacts:

## Setup 

- UserContact Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST

## Broker

- UserContact Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- UserContact Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- UserContact Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- UserContact Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST

## Service

- UserContact Service Add function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- UserContact Service Retrieve by Id function @eriadhami  by Wednesday 12:00 AM - 11:59 PM PST
- UserContact Service Retrieve All function @devmanzur by Wednesday 12:00 AM - 11:59 PM PST
- UserContact Service Delete by Id function @tobidub by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- UserContact Controller Post endpoint @eriadhami  by Thursday 12:00 AM - 11:59 PM PST
- UserContact Controller Get by Id endpoint @eriadhami  by Thursday 12:00 AM - 11:59 PM PST
- UserContact Controller Get All endpoint @eriadhami  by Thursday 12:00 AM - 11:59 PM PST
- UserContact Controller Delete endpoint @eriadhami  by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- UserContact Post Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- UserContact Update Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- UserContact Get All Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an UserContact this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by eriadhami** [comment]
> ## Service
> * Exam Service Retrieve All function @devmanzur by Wednesday 12:00 AM - 11:59 PM PST
> * Exam Service Modify function @hassanhabib by Wednesday 12:00 AM - 11:59 PM PST

If anyone (@hassanhabib or @devmanzur) does not have time for the above tasks, I would be happy to help after Friday 06:00 AM PST. Thanks
