### ISSUE TITLE
CODE RUB: Indent Parameters

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/OtripleS#2200]
https://github.com/hassanhabib/OtripleS/blob/master/OtripleS.Web.Api/Services/Foundations/AssignmentAttachments/AssignmentAttachmentService.Validations.cs

Line 50 needs to be broker into 2 parts

**Comment by ElbekDeveloper** [comment]
Assigned to @hoxhaleo319

**Comment by hoxhaleo319** [comment]
@ElbekDeveloper I made the change to move line 50 to it's separate line.

**Comment by ShriHumrudha** [comment]
Closed via #2214
