### ISSUE TITLE
Calendar Entry Model Discussion

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#227]
We need to think of a model to represent an entry in a calendar, here's some high level requirements:

- It needs to represent a label and a description
- It might require attaching a file 
- It needs to have a start date and an end date 
- Might need a reminder time (1 day before it occurs for instance)

Let's think together about any other information we might need in a calendar entry.

**Comment by stasnowak** [comment]
public class CalendarEntry : IAuditable
    {
        public Guid Id { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public DateTimeOffset StartDate { get; set; }
        public DateTimeOffset EndDate { get; set; }
        public bool IsAllDay { get; set; }
        public DateTimeOffset RemindAtDateTime { get; set; }
        public RemindBy RemindBy { get; set; }
        public IEnumerable<byte[]> Attachements { get; set; }

        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }
    public enum RemindBy
    {
        Mail,
        Phone,
        Notification
    }

    //Alternatively there is maybe an option using an enum for RemindAtDateTime as RemindBeforeStartDate 
    //but it's taking away flexible implementation later on.
    public enum RemindBeforeStartDate
    {
        QuarterHour,
        HalfHour,
        Hour,
        Day,
        Week
    }

    //Additionally Tags could be used to later be able to find 
    //entries by categories or highlight exams and others
    public IEnumerable<string> Tags { get; set; }

    //Since it is my first contribution i want to say hay.
    //Keep up with the great Project. Greetings from Germany.

**Comment by a-urel** [comment]
@hassanhabib Do you mean course schedules or a generic calendar?

**Comment by AgentEnder** [comment]
For calendar entries we should try to follow iCal specification, to allow people to easily import / export entries.

The RFC for that spec is here: https://tools.ietf.org/html/rfc5545

**Comment by hassanhabib** [comment]
@a-urel generic schedule - like an outlook calendar for instance.
The thing about this schedule entries though is that it should have visibility based on the user type (student, teacher, admin ...etc)
In this sense a course calendar would be just another entry on the community calendar.
What do you think?

**Comment by hassanhabib** [comment]
@AgentEnder any particular model you can extract out of this standard you shared?

**Comment by hassanhabib** [comment]
@stasnowak this is beautiful - thanks for sharing.
Anyone has any follow ups on @stasnowak proposed model?

**Comment by a-urel** [comment]
I think recurrence is crucial in this use case.

**Comment by stasnowak** [comment]
@a-urel hay i was thinking also about recurring events, but i think a single calendar entry should not know anything about other entries. further down in the UI a component could be build that will create many entries for recurrence. In other case it would be difficult to track when you want to delete one entry of an series for example or reschedule an single day.

**Comment by a-urel** [comment]
@stasnowak I think including recurrence info in calendar entry is the simplest design.
This is not a very simple problem. Recurrence exceptions (edited, deleted) should create physical records.
But physical records may be required in some other cases, too.

A third party schedular tool (e.g. DevExpress, Syncfusion, etc.) would simplify this task. Syncfusion have a free community license,
@hassanhabib what do you think about using third party tools?

**Comment by stasnowak** [comment]
@a-urel I understand you. Let's say we create a recurring calendar entry it would have the same label. Maybe an operation like DeleteByLabel could provide an solution, but then again what when the names occurrences in other entries that are not a part of the series you want to delete. In that case i think you are right and an Recurrence Model addition is needed.

**Comment by hassanhabib** [comment]
@a-urel  for the UI (Blazor) we will be using Syncfusion - but we don't want external libraries models to leak into our business logic - we want to create our own native models to ensure flexibility and decoupling from any external resources.

**Comment by hassanhabib** [comment]
I will be posting the assignments and the next model discussion tonight

**Comment by hassanhabib** [comment]
This week, we are going to build the foundation entity for a CalendarEntry - CalendarEntrys are very common in schooling systems for all involved members, teachers, students, admins and guardians/parents.
We want to offer a pipeline/solution for a community CalendarEntry for the entire school plus a personalized CalendarEntry entity for each and every individual to fit just their schedules.

the following is just the root entity that's going to be referenced by other CalendarEntry entries, here we go:

```csharp

    public class CalendarEntry : IAuditable
    {
        public Guid Id { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public DateTimeOffset StartDate { get; set; }
        public DateTimeOffset EndDate { get; set; }
        public bool IsAllDay { get; set; }
        public DateTimeOffset RemindAtDateTime { get; set; }
        public RecurrenceType RecurrenceType { get; set; }
        public int Period { get; set; }
        public int RepeatCount { get; set; }
        public DateTimeOffset? RepeatUntil { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }

        public Guid CalendarId { get; set; }
        public Calendar Calendar { get; set; }
    }

```

Since this is not a very deep model for discussion I am going to go ahead with the assignments directly as follows:


## Setup 

- CalendarEntry Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST [done]

## Broker

- CalendarEntry Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- CalendarEntry Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- CalendarEntry Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- CalendarEntry Broker Update function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]
- CalendarEntry Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST [done]

## Service

- CalendarEntry Service Add function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST 
- CalendarEntry Service Retrieve All function @stasnowak by Wednesday 12:00 AM - 11:59 PM PST 
- CalendarEntry Service Retrieve by Id function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- CalendarEntry Service Modify function @tobidub by Wednesday 12:00 AM - 11:59 PM PST 
- CalendarEntry Service Delete by Id function @hassanhabib Wednesday 12:00 AM - 11:59 PM PST

## Controller

- CalendarEntry Controller Post endpoint @Jamaxack  by Thursday 12:00 AM - 11:59 PM PST
- CalendarEntry Controller Get All endpoint @Jamaxack by Thursday 12:00 AM - 11:59 PM PST
- CalendarEntry Controller Get by Id endpoint @Jamaxackby Thursday 12:00 AM - 11:59 PM PST
- CalendarEntry Controller Put endpoint @Jamaxackby Thursday 12:00 AM - 11:59 PM PST
- CalendarEntry Controller Delete endpoint @Jamaxack by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- CalendarEntry Post Acceptance Test @JaAfghan by Friday 12:00 AM - 11:59 PM PST
- CalendarEntry Get All Acceptance Test @tajwal  by Friday 12:00 AM - 11:59 PM PST
- CalendarEntry Update Acceptance Test @JaAfghan by Friday 12:00 AM - 11:59 PM PST
- CalendarEntry Delete Acceptance Test @tajwal
