### ISSUE TITLE
CODE RUB: Change file name from TeacherContacts.cs to TeacherContact.cs

### ISSUE THREAD

**Issue by Spectralgo** [hassanhabib/OtripleS#2313]

**Comment by Rashidovicc** [comment]
I changed this issue

**Comment by Rashidovicc** [comment]
![image](https://user-images.githubusercontent.com/105649270/188842913-5670e3f4-22b9-4cb0-8f7d-0f7f9f5ddad6.png)
I change this issue but I can't push @Spectralgo

**Comment by Spectralgo** [comment]
Hi @Rashidovicc :) Did you fork the repo to your own account and then cloned it from there or did you cmon it directly from this repo?

**Comment by Rashidovicc** [comment]
@Spectralgo I cloned directly from this repo
Should I fork and then clone?

**Comment by Spectralgo** [comment]
Yes

**Comment by Rashidovicc** [comment]
ok I understand

**Comment by Spectralgo** [comment]
@Rashidovicc fork, and then clone it from tou own repo. The pull request button should appear on your GitHub account after you pushed the changes to you own repo

**Comment by Dastanbayev** [comment]
> @Rashidovicc fork, and then clone it from tou own repo. The pull request button should appear on your GitHub account after you pushed the changes to you own repo

After the fork, should I create a new branch and push to this branch or to my 'master' branch?

**Comment by Dastanbayev** [comment]
@Rashidovicc everything is ok.

**Comment by Spectralgo** [comment]
Do not merge to your master, just push your branch to GitHub and do he pull request.
