### ISSUE TITLE
old packages

### ISSUE THREAD

**Issue by MuhammadKasimov** [hassanhabib/OtripleS#2417]
Hello everyone I'm Muhammad Muhammad Kasimov and I wanted to contribute OrtipleS project I found that there were installed packages for dotnet 6 but project in 7.
There are preview versions of EntityFramework but for example Swashbuckle.AspNetCore latest version is for dotnet 6

**Comment by ElbekDeveloper** [comment]
Hi @MuhammadKasimov. I hope you are doing great. EF had issues with latest version. Please, watch this video to learn more about this issue and how Ustadh @hassanhabib has fixed it during the recording https://www.youtube.com/watch?v=V7fCqKjN4zA

**Comment by MuhammadKasimov** [comment]
Hello @ElbekDeveloper thanks for answer

**Comment by ElbekDeveloper** [comment]
I think this can be closed now
