### ISSUE TITLE
warning for "DRY" principles.

### ISSUE THREAD

**Issue by MuhammadUmarqulov** [hassanhabib/OtripleS#2422]
with it, there is a violation of the DRY principle
partial classes "StorageBroker" that can have the generic name function ("SelectByIdAsync", "InsertAsync", "DeleteAsync",
"UpdateAsync", "SelectAll") bodies have the same idea. you should avoid this by using generic classes

_If you let me know if my idea is valid, I would contribute to this project._

**Comment by ElbekDeveloper** [comment]
this would entangle the application. As a result, it becomes harder to decouple and split into microservices later on. Remember we build monolith with microservices in mind

DRY is a double-edged sword. You should know the exact limit where to apply it.
