### ISSUE TITLE
Warning For DRY Princple in Services

### ISSUE THREAD

**Issue by Maksudovich** [hassanhabib/OtripleS#2426]
Ortiples.Web.Api.Services.Foundations 
There are lines that do not meet the dry principle. only 4 brokers are used in all services, these should be taken out separately as an abstract class.

**Comment by Maksudovich** [comment]
> Ortiples.Web.Api.Services.Foundations There are lines that do not meet the dry principle. only 4 brokers are used in all services, these should be taken out separately as an abstract class.

@hassanhabib

**Comment by ElbekDeveloper** [comment]
@Maksudovich this would entangle the application. As a result, it becomes harder to decouple and split into microservices later on. Remember we build monolith with microservices in mind


DRY is a double-edged sword. You should know the exact limit where to apply it.

**Comment by Maksudovich** [comment]
ok thank's

**Comment by Rashidovicc** [comment]
@ElbekDeveloper this issue should be closed.
