### ISSUE TITLE
Attachment Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#243]
This upcoming sprint we want to discuss `Attachment` model, here's a draft model:

```csharp
class Attachment 
{
     public Guid {get; set;}
     public string Label {get; set;}
     public string Description {get; set;}
     public byte[] Contents {get; set;}
}
```

**Comment by tajwal** [comment]
what about ContectType/extension(word, Pdf,images), we can later on benefit from it.

**Comment by hassanhabib** [comment]
@tajwal that's a good idea.

**Comment by viralpandya** [comment]
We need url as well, in case if we are going to store documents in cloud

**Comment by hassanhabib** [comment]
Tasks & Assignments should be posted here tomorrow night

**Comment by hassanhabib** [comment]
This week, we are going to build the foundation entity for a Attachment - Attachments are very common in schooling systems for all involved members, teachers, students, admins and guardians/parents.
We want to offer a pipeline/solution for a community Attachment for the entire school plus a personalized Attachment entity for each and every individual to fit just their schedules.

the following is just the root entity that's going to be referenced by other Attachment entries, here we go:

```csharp
public class Attachment : IAuditable
    {
        public Guid Id { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public byte[] Contents { get; set; }
        public string ContectType { get; set; }
        public string Extension { get; set; }
        public string ExternalUrl { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }
```

Since this is not a very deep model for discussion I am going to go ahead with the assignments directly as follows:


## Setup 

- Attachment Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST [done]

## Broker

- Attachment Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- Attachment Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- Attachment Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- Attachment Broker Update function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- Attachment Broker Delete function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST

## Service

- Attachment Service Add function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST 
- Attachment Service Retrieve All function @stasnowak by Wednesday 12:00 AM - 11:59 PM PST 
- Attachment Service Retrieve by Id function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- Attachment Service Modify function @tobidub by Wednesday 12:00 AM - 11:59 PM PST 
- Attachment Service Delete by Id function @hassanhabib Wednesday 12:00 AM - 11:59 PM PST

## Controller

- Attachment Controller Post endpoint @Jamaxack  by Thursday 12:00 AM - 11:59 PM PST
- Attachment Controller Get All endpoint @Jamaxack by Thursday 12:00 AM - 11:59 PM PST
- Attachment Controller Get by Id endpoint @Jamaxackby Thursday 12:00 AM - 11:59 PM PST
- Attachment Controller Put endpoint @Jamaxackby Thursday 12:00 AM - 11:59 PM PST
- Attachment Controller Delete endpoint @Jamaxack by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- Attachment Post Acceptance Test @JaAfghan by Friday 12:00 AM - 11:59 PM PST
- Attachment Get All Acceptance Test @tajwal  by Friday 12:00 AM - 11:59 PM PST
- Attachment Update Acceptance Test @JaAfghan by Friday 12:00 AM - 11:59 PM PST
- Attachment Delete Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST

**Comment by eriadhami** [comment]
> - Attachment Service Delete by Id function @hassanhabib Wednesday 12:00 AM - 11:59 PM PST
> 

@hassanhabib do you want me to finish this task?

**Comment by hassanhabib** [comment]
> > - Attachment Service Delete by Id function @hassanhabib Wednesday 12:00 AM - 11:59 PM PST
> > 
> 
> @hassanhabib do you want me to finish this task?

@eriadhami sure thing - thank you.

**Comment by hassanhabib** [comment]
@viralpandya please take care of the acceptance tests for Attachments so we can close this issue - I have re-assigned the tasks to you.

**Comment by viralpandya** [comment]
@hassanhabib : Sure
