### ISSUE TITLE
Calendar with A that got named Calender with E

### ISSUE THREAD

**Issue by stasnowak** [hassanhabib/OtripleS#245]
@hassanhabib  I noticed that we write sometimes calend**a**r and sometimes calend**e**r and this happens to me too all the time. In the variable declaration it is maybe not important but not beautiful, but saw some occurrences in the namespaces and test method names. Can i fix it for us in an pull request, or how you want to handle issues like this one?

**Comment by hassanhabib** [comment]
@stasnowak we should change them all to Calendar good point

**Comment by stasnowak** [comment]
ok i can take care of it. I will do so after the one pull request #242 is merged, else i don't know if its gonna work well because it also is using some misspelled calendars

**Comment by stasnowak** [comment]
@hassanhabib can be closed after merging #247
