### ISSUE TITLE
Throwing exceptions

### ISSUE THREAD

**Issue by mooohi** [hassanhabib/OtripleS#2518]
Salam,

please check this 
```
public async Task ShouldThrowCriticalDependencyExceptionOnRegisterIfSqlErrorOccursAndLogItAsync()
```
it throws an exception in
```
this.dateTimeBrokerMock.Setup(broker =>
                broker.GetCurrentDateTime())
                    .Throws(sqlException);
```
I believe it should be
```
this.storageBrokerMock.Setup(broker =>
                broker.InsertStudentAsync(someStudent))
                .ThrowsAsync(sqlException);
```

I've seen this practice done on many tests. 

Was that intentional?

Regards

**Comment by artisansol** [comment]
Hello @mooohi I had similar query. Refer below twitter thread for clarification.  In short, use of datetimebroker is also correct.
https://twitter.com/kajepratik/status/1645839323156054029

**Comment by mooohi** [comment]
Got it. 

Thanks, @artisansol
