### ISSUE TITLE
Student Attachments

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#257]
This week we will be setting up attachment to a student profile, a simple many to many relationship to attach the two entities:

```csharp
public class StudentAttachment
{
    public Guid studentId {get; set;}
    public Guid attachmentId {get; set;}
    public Guid Notes {get; set;}
}
```

**Comment by hassanhabib** [comment]
*** IMPORTANT ***
I will be holding off on assignments, give everyone some time off this week, we should start again our work on Monday Jan 4th - enjoy the time off talk to you all soon.

**Comment by hassanhabib** [comment]
I will be posting the assignments for this feature shortly

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our StudentAttachment entity model this week:

```csharp
public class StudentAttachment {
    public Guid StudentId {get; set;}
    public Student Student {get; set;}
    public Guid AttachmentId {get; set;}
    public Attachment Attachment {get; set;}
    public string Notes {get; set;}
}
```
Now, let's talk about StudentAttachments:

## Setup 

- StudentAttachment Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST

## Broker

- StudentAttachment Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- StudentAttachment Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- StudentAttachment Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- StudentAttachment Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST

## Service

- StudentAttachment Service Add function @tobidub  by Wednesday 12:00 AM - 11:59 PM PST
- StudentAttachment Service Retrieve by Id function @eriadhami  by Wednesday 12:00 AM - 11:59 PM PST
- StudentAttachment Service Retrieve All function @stasnowak by Wednesday 12:00 AM - 11:59 PM PST
- StudentAttachment Service Delete by Id function @Jamaxack by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- StudentAttachment Controller Post endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentAttachment Controller Get by Id endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentAttachment Controller Get All endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentAttachment Controller Delete endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- StudentAttachment Post Acceptance Test @hassanhabib by Friday 12:00 AM - 11:59 PM PST
- StudentAttachment Update Acceptance Test @hassanhabib   by Friday 12:00 AM - 11:59 PM PST
- StudentAttachment Get All Acceptance Test @hassanhabib  by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an StudentAttachment this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by viralpandya** [comment]
@hassanhabib : Do we want to keep versioning of an attachment?

**Comment by hassanhabib** [comment]
@viralpandya let's keep it simple for now - and react based on what schools need

**Comment by viralpandya** [comment]
@Jamaxack  and @tobidub : Sorry I had to complete worktime assigned to you as I needed it for controller work to be completed on Thursday. I hope you do not mind. Please message me anytime when anyone of our teammate is crumbling with time management or resource. I will be happy to help.
