### ISSUE TITLE
Calendar Entry Attachment Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#281]
```csharp
public class CalendarEntryAttachment
{
    public Guid CalendarEntryId {get; set;}
    public Guid AttachmentId {get; set;}
    public Guid Notes {get; set;}
}
```

**Comment by hassanhabib** [comment]
I will be posting the assignments tonight

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our CalendarEntryAttachment entity model this week:

```csharp
public class CalendarEntryAttachment {
    public Guid CalendarEntryId {get; set;}
    public CalendarEntry CalendarEntry {get; set;}
    public Guid AttachmentId {get; set;}
    public Attachment Attachment {get; set;}
    public string Notes {get; set;}
}
```
Now, let's talk about CalendarEntryAttachments:

## Setup 

- CalendarEntryAttachment Model Setup & Migrations with EF Core @viralpandya Tuesday 12:00 AM - 11:59 PM PST

## Broker

- CalendarEntryAttachment Broker Select By Id function @viralpandya by Tuesday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Broker Select All function @viralpandya by Tuesday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Broker Insert function @viralpandya by Tuesday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Broker Delete function @viralpandya by Tuesday 12:00 AM - 11:59 PM PST

## Service

- CalendarEntryAttachment Service Add function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Service Retrieve by Id function @Jamaxack by Wednesday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Service Retrieve All function @bilalmehrban by Wednesday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Service Delete by Id function @ZionLloyd05 by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- CalendarEntryAttachment Controller Post endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Controller Get by Id endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Controller Get All endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Controller Delete endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- CalendarEntryAttachment Post Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Get All Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- CalendarEntryAttachment Delete Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST

## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the CalendarEntryService, CalendarEntry and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an CalendarEntryAttachment this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by eriadhami** [comment]
Please, can anybody take over my task for this week only?

**Comment by ZionLloyd05** [comment]
I can help cover up for your task.

**Comment by eriadhami** [comment]
> I can help cover up for your task.

@ZionLloyd05 Many thanks. Much appreciated

**Comment by bilalmehrban** [comment]
@ZionLloyd05 I am also available to cover up the task for eriadhami. if you need any help, do let me know.

**Comment by ZionLloyd05** [comment]
> @ZionLloyd05 I am also available to cover up the task for eriadhami. if you need any help, do let me know.  

Great! I'll let you know as soon as I need some help.

**Comment by ZionLloyd05** [comment]
> @ZionLloyd05 I am also available to cover up the task for eriadhami. if you need any help, do let me know.  

Hi @bilalmehrban, could you please start up with eriadhami's task, so we can be much faster..

**Comment by bilalmehrban** [comment]
@ZionLloyd05 I have done mines. I will send PR for eriadhami's task as well tomorrow.

**Comment by viralpandya** [comment]
I should be done with controller and acceptance tests tomorrow when All CRID operations for service are merged.

**Comment by viralpandya** [comment]
I have worked on Delete and Add PR to try to complete them as per standards and starting to work on my assignment.
