### ISSUE TITLE
Course Attachment

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#288]
```csharp
public class CourseAttachment
{
    public Guid CourseId {get; set;}
    public Guid AttachmentId {get; set;}
    public Guid Notes {get; set;}
}
```

Hit the like button on this post if you'd like to be a part of developing this feature

**Comment by hassanhabib** [comment]
I will posting the assignments on this Monday night

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our CourseAttachment entity model this week:

```csharp
public class CourseAttachment {
    public Guid CourseId {get; set;}
    public Course Course {get; set;}
    public Guid AttachmentId {get; set;}
    public Attachment Attachment {get; set;}
    public string Notes {get; set;}
}
```
Now, let's talk about CourseAttachments:

## Setup 

- CourseAttachment Model Setup & Migrations with EF Core @bilalmehrban Tuesday 12:00 AM - 11:59 PM PST

## Broker

- CourseAttachment Broker Select By Id function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- CourseAttachment Broker Select All function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- CourseAttachment Broker Insert function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- CourseAttachment Broker Delete function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST

## Service

- CourseAttachment Service Add function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- CourseAttachment Service Retrieve by Id function @viralpandya  by Wednesday 12:00 AM - 11:59 PM PST
- CourseAttachment Service Retrieve All function @stasnowak by Wednesday 12:00 AM - 11:59 PM PST
- CourseAttachment Service Delete by Id function @ZionLloyd05 by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- CourseAttachment Controller Post endpoint @hassanhabib by Thursday 12:00 AM - 11:59 PM PST
- CourseAttachment Controller Get by Id endpoint @hassanhabib  by Thursday 12:00 AM - 11:59 PM PST
- CourseAttachment Controller Get All endpoint @hassanhabib  by Thursday 12:00 AM - 11:59 PM PST
- CourseAttachment Controller Delete endpoint @hassanhabib  by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- CourseAttachment Post Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- CourseAttachment Get All Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- CourseAttachment Delete Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST

## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the CourseService, Course and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an CourseAttachment this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by eriadhami** [comment]
> Thank you all for your contributions, here's an overview of our CourseAttachment entity model this week:
> 
> 
> 
> ```csharp
> 
> public class CourseAttachment {
> 
>     public Guid CourseId {get; set;}
> 
>     public Course Course {get; set;}
> 
>     public Guid AttachmentId {get; set;}
> 
>     public Attachment Attachment {get; set;}
> 
>     public string Notes {get; set;}
> 
> }
> 
> ```
> 
> Now, let's talk about CourseAttachments:
> 
> 
> 
> ## Setup 
> 
> 
> 
> - CourseAttachment Model Setup & Migrations with EF Core @bilalmehrban Tuesday 12:00 AM - 11:59 PM PST
> 
> 
> 
> ## Broker
> 
> 
> 
> - CourseAttachment Broker Select By Id function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Broker Select All function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Broker Insert function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Broker Delete function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
> 
> 
> 
> ## Service
> 
> 
> 
> - CourseAttachment Service Add function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Service Retrieve by Id function @viralpandya  by Wednesday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Service Retrieve All function @stasnowak by Wednesday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Service Delete by Id function @ZionLloyd05 by Wednesday 12:00 AM - 11:59 PM PST
> 
> 
> 
> ## Controller
> 
> 
> 
> - CourseAttachment Controller Post endpoint @hassanhabib by Thursday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Controller Get by Id endpoint @hassanhabib  by Thursday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Controller Get All endpoint @hassanhabib  by Thursday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Controller Delete endpoint @hassanhabib  by Thursday 12:00 AM - 11:59 PM PST
> 
> 
> 
> 
> 
> ## Acceptance Tests
> 
> 
> 
> - CourseAttachment Post Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Get All Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
> 
> - CourseAttachment Delete Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
> 
> 
> 
> ## Contribution Rules:
> 
> 1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
> 
> 2. All CRUD operations now have similar functionality in the CourseService, Course and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
> 
> 3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
> 
> 4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.
> 
> 
> 
> If you haven't had an CourseAttachment this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.
> 
> 
> 
> As soon as all these tasks are done, this issue will be closed.
> 
> 
> 
> Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.
> 
> 

Can anybody help me with my task please? I tested positive for Covid-19.

**Comment by stasnowak** [comment]
@eriadhami I will take care. Hope you get better as fast as possible

**Comment by eriadhami** [comment]
@stasnowak thanks a lot. Much appreciated

**Comment by hassanhabib** [comment]
@eriadhami take it easy brother. Wish you a healthy and speedy recovery.
