### ISSUE TITLE
Discuss Teacher Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#3]
Hi everyone,
This week we want to discuss the Teacher model - here's an initial concept:

```csharp
public class Teacher : IAuditable
{
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public DateTimeOffset BirthDate { get; set; }
        public Gender Gender { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid UpdatedBy { get; set; }
}
```

There's one thing here to consider:
The teacher model seems almost identical to the Student model, can you think of any additional properties that a teacher model should have that a student wouldn't?

**Comment by AgentEnder** [comment]
Maybe we could extract a lot of the common properties to a base entity (or
interface) here, so we have IPerson with fields

First Name,
Last Name,
Gender

Etc.

As far as further fields needed for teachers they would likely have an
assigned department (soc. Studies, math etc), or in higher education they
might belong to a certain college in this same way (college of math,
business etc)

**Comment by Driedas** [comment]
it may be too soon for trying to factor out common interfaces just for the sake of it describing things that are common. Interfaces represent some common functionality or behavior which makes a lot of sense for an interface like IAuditable (even as just a marker interface to handle cross-cutting concerns - describe something that needs to be audited).
There is no core domain use case yet (that I know or can think of) that would be common to a teacher and student based on their names.

**Comment by hassanhabib** [comment]
@AgentEnder I'm going to have to agree with @Driedas here - let's no try to build common _things_ not just yet - let's build every service as if it was meant to be split completely into it's own microservice - we are building a monolith with a microservice mindset so it's easy to break apart later and scale based on the most commonly used features.

**Comment by AgentEnder** [comment]
Gotcha, the ease of splitting it up is definitely something that I had not considered.   From: Hassan Rezk HabibSent: Monday, June 29, 2020 8:40 AMTo: hassanhabib/OtripleSCc: Craigory V Coppola; MentionSubject: Re: [hassanhabib/OtripleS] Discuss Teacher Model (#3) @AgentEnder I'm going to have to agree with @Driedas here - let's not try to build common things not just yet - let's build every service as if it was meant to be split completely into it's own microservice - we are building a monolith with a microservice mindset so it's easy to break apart later and scale based on the most commonly used features.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Driedas** [comment]
@hassanhabib nothing comes to my mind that should be a part of the Teacher entity. There will be plenty more once the rubber hits the road and we start to implement some use cases, but I see it mostly in related entities (subjects and their level the teacher is teaching, experience, grading, homework, etc etc etc)

**Comment by devmanzur** [comment]
I guess we could include what subject the teacher specializes in. he may be an expert in multiple subjects like physics, mathematics, etc. So we can only assign teachers to subjects he is good with.

**Comment by devmanzur** [comment]
as well as his educational qualifications

**Comment by a-urel** [comment]
Maybe two more properties can be added:
**SSN** *(Social Security Number)*
**Title** *(Academic title eg. Professor, Associate Professor, Lecturer, Instructor, etc.)*

**Comment by AgentEnder** [comment]
We should ensure that SSN’s are stored encrypted if we are storing them in the database   From: AhmetSent: Monday, June 29, 2020 5:02 PMTo: hassanhabib/OtripleSCc: Craigory V Coppola; MentionSubject: Re: [hassanhabib/OtripleS] Discuss Teacher Model (#3) Maybe two more properties can be added:SSN (Social Security Number)Title (Academic title eg. Professor, Associate Professor, Lecturer, Instructor, etc.)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hassanhabib** [comment]
> Maybe two more properties can be added:
> **SSN** _(Social Security Number)_
> **Title** _(Academic title eg. Professor, Associate Professor, Lecturer, Instructor, etc.)_

@a-urel wouldn't SSN along with other legal identifications be a part of a separate entity? 
Also, I think SSN is a U.S specific, maybe Europe but not as global I think.

**Comment by tajwal** [comment]
> Hi everyone,
> This week we want to discuss the Teacher model - here's an initial concept:
> 
> ```cs
> public class Student : IAuditable
> {
>         public Guid Id { get; set; }
>         public string UserId { get; set; }
>         public string EmployeeNumber { get; set; }
>         public string FirstName { get; set; }
>         public string MiddleName { get; set; }
>         public string LastName { get; set; }
>         public DateTimeOffset BirthDate { get; set; }
>         public Gender Gender { get; set; }
>         public DateTimeOffset CreatedDate { get; set; }
>         public Guid CreatedBy { get; set; }
>         public DateTimeOffset UpdatedDate { get; set; }
>         public Guid UpdatedBy { get; set; }
> }
> ```
> 
> There's one thing here to consider:
> The teacher model seems almost identical to the Student model, can you think of any additional properties that a teacher model should have that a student wouldn't?

Mr. @hassanhabib I think below properties for school staff is required regardless of its nature of job, and for sure those will not fit in one model/table and may need many tables.

Status(Active, resigned or terminated),
MaritalStatus(Single,Marid,Widowed and Diverced)
Title,
Workship in case there are many working ships per day,
Joining(StartDate), 
endDate,
NationalIdNumber,
PassportNumber,Issue and Expire Dates,
Photo,
Tax Identification Number(TIN),
EmployeeType(Permanent, contractual or service),
BloodGroup,
DrivingLicenseNumber, Issue and Expire Dates,
MobileNumber,
AltMobileNumber,
Email.
Addresses(current & permanent),
Salary grid and other payroll related properties.

**Comment by a-urel** [comment]
> > Maybe two more properties can be added:
> > **SSN** _(Social Security Number)_
> > **Title** _(Academic title eg. Professor, Associate Professor, Lecturer, Instructor, etc.)_
> 
> @a-urel wouldn't SSN along with other legal identifications be a part of a separate entity?
> Also, I think SSN is a U.S specific, maybe Europe but not as global I think.

I think *employee* specific fields can be part of a separate entity.
Such as SSN(?), Position, Department, Manager, employee type, start date, etc.

**Comment by devmanzur** [comment]
following suggestion by @a-urel


```
public class Teacher: IAuditable
{
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public DateTimeOffset BirthDate { get; set; }
        public Gender Gender { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid UpdatedBy { get; set; }

        public Designation Designation { get; set; }

       //  I think this property is very important for teachers, 
      // whether we decide to keep it here or create a separate class to hold such data is a matter of discussion.
        public DateTimeOffset JoiningDate{ get; set; }
}

public enum Designation{
        Professor,
        Associate Professor,
        Lecturer,
        Instructor
}

```

**Comment by eriadhami** [comment]
Here in Albania (and I think in Europe) teacher also are Tutors of some students (grouped in classes), maybe later we will need also a Class model and an one to one relation with the Teacher model

**Comment by devmanzur** [comment]
> Here in Albania (and I think in Europe) teacher also are Tutors of some students (grouped in classes), maybe later we will need also a Class model and an one to one relation with the Teacher model

we can manage that using a Teacher-Student type of relation later.

**Comment by tajwal** [comment]
> following suggestion by @a-urel
> 
> ```
> public class Teacher: IAuditable
> {
>         public Guid Id { get; set; }
>         public string UserId { get; set; }
>         public string EmployeeNumber { get; set; }
>         public string FirstName { get; set; }
>         public string MiddleName { get; set; }
>         public string LastName { get; set; }
>         public DateTimeOffset BirthDate { get; set; }
>         public Gender Gender { get; set; }
>         public DateTimeOffset CreatedDate { get; set; }
>         public Guid CreatedBy { get; set; }
>         public DateTimeOffset UpdatedDate { get; set; }
>         public Guid UpdatedBy { get; set; }
> 
>         public Designation Designation { get; set; }
> 
>        //  I think this property is very important for teachers, 
>       // whether we decide to keep it here or create a separate class to hold such data is a matter of discussion.
>         public DateTimeOffset JoiningDate{ get; set; }
> }
> 
> public enum Designation{
>         Professor,
>         Associate Professor,
>         Lecturer,
>         Instructor
> }
> ```

Dear @devmanzur in case of having separated entity for  employment information then joining date and Designation will moved there as a teacher/employees can have many designations and start and end dates  during his/her stay in school even the joining date is same it will also move there.

**Comment by devmanzur** [comment]
> > following suggestion by @a-urel
> > ```
> > public class Teacher: IAuditable
> > {
> >         public Guid Id { get; set; }
> >         public string UserId { get; set; }
> >         public string EmployeeNumber { get; set; }
> >         public string FirstName { get; set; }
> >         public string MiddleName { get; set; }
> >         public string LastName { get; set; }
> >         public DateTimeOffset BirthDate { get; set; }
> >         public Gender Gender { get; set; }
> >         public DateTimeOffset CreatedDate { get; set; }
> >         public Guid CreatedBy { get; set; }
> >         public DateTimeOffset UpdatedDate { get; set; }
> >         public Guid UpdatedBy { get; set; }
> > 
> >         public Designation Designation { get; set; }
> > 
> >        //  I think this property is very important for teachers, 
> >       // whether we decide to keep it here or create a separate class to hold such data is a matter of discussion.
> >         public DateTimeOffset JoiningDate{ get; set; }
> > }
> > 
> > public enum Designation{
> >         Professor,
> >         Associate Professor,
> >         Lecturer,
> >         Instructor
> > }
> > ```
> 
> Dear @devmanzur in case of having separated entity for employment information, then joining date and designation will moved there as a teacher/employees can have many designations and start and end dates during his/her stay in school even the joining date is same it will also move.

agreed

**Comment by hassanhabib** [comment]
In the Student Issue - people are talking about a status for the teacher, we should probably start thinking about all the statuses a teacher entity might have.

**Comment by AgentEnder** [comment]
Potential statuses:

New Hire
Active
Retired
Terminated

**Comment by JaAfghan** [comment]
> > following suggestion by @a-urel
> > ```
> > public class Teacher: IAuditable
> > {
> >         public Guid Id { get; set; }
> >         public string UserId { get; set; }
> >         public string EmployeeNumber { get; set; }
> >         public string FirstName { get; set; }
> >         public string MiddleName { get; set; }
> >         public string LastName { get; set; }
> >         public DateTimeOffset BirthDate { get; set; }
> >         public Gender Gender { get; set; }
> >         public DateTimeOffset CreatedDate { get; set; }
> >         public Guid CreatedBy { get; set; }
> >         public DateTimeOffset UpdatedDate { get; set; }
> >         public Guid UpdatedBy { get; set; }
> > 
> >         public Designation Designation { get; set; }
> > 
> >        //  I think this property is very important for teachers, 
> >       // whether we decide to keep it here or create a separate class to hold such data is a matter of discussion.
> >         public DateTimeOffset JoiningDate{ get; set; }
> > }
> > 
> > public enum Designation{
> >         Professor,
> >         Associate Professor,
> >         Lecturer,
> >         Instructor
> > }
> > ```
> 
> Dear @devmanzur in case of having separated entity for employment information, then joining date and designation will moved there as a teacher/employees can have many designations and start and end dates during his/her stay in school even the joining date is same it will also move.

Dear @devmanzur  I am agreed with @tajwal  As per Standard Microsoft ERP Structured Separated entity for Employment information will be much better

**Comment by hassanhabib** [comment]
> > > following suggestion by @a-urel
> > > ```
> > > public class Teacher: IAuditable
> > > {
> > >         public Guid Id { get; set; }
> > >         public string UserId { get; set; }
> > >         public string EmployeeNumber { get; set; }
> > >         public string FirstName { get; set; }
> > >         public string MiddleName { get; set; }
> > >         public string LastName { get; set; }
> > >         public DateTimeOffset BirthDate { get; set; }
> > >         public Gender Gender { get; set; }
> > >         public DateTimeOffset CreatedDate { get; set; }
> > >         public Guid CreatedBy { get; set; }
> > >         public DateTimeOffset UpdatedDate { get; set; }
> > >         public Guid UpdatedBy { get; set; }
> > > 
> > >         public Designation Designation { get; set; }
> > > 
> > >        //  I think this property is very important for teachers, 
> > >       // whether we decide to keep it here or create a separate class to hold such data is a matter of discussion.
> > >         public DateTimeOffset JoiningDate{ get; set; }
> > > }
> > > 
> > > public enum Designation{
> > >         Professor,
> > >         Associate Professor,
> > >         Lecturer,
> > >         Instructor
> > > }
> > > ```
> > 
> > 
> > Dear @devmanzur in case of having separated entity for employment information, then joining date and designation will moved there as a teacher/employees can have many designations and start and end dates during his/her stay in school even the joining date is same it will also move.
> 
> Dear @devmanzur I am agreed with @tajwal As per Standard Microsoft ERP Structured Separated entity for Employment information will be much better

Please remember that this only for schools, not colleges or universities - just schools until high school - so professors and such out of the scope of this project.

**Comment by AgentEnder** [comment]
> > > > following suggestion by @a-urel
> > > > ```
> > > > public class Teacher: IAuditable
> > > > {
> > > >         public Guid Id { get; set; }
> > > >         public string UserId { get; set; }
> > > >         public string EmployeeNumber { get; set; }
> > > >         public string FirstName { get; set; }
> > > >         public string MiddleName { get; set; }
> > > >         public string LastName { get; set; }
> > > >         public DateTimeOffset BirthDate { get; set; }
> > > >         public Gender Gender { get; set; }
> > > >         public DateTimeOffset CreatedDate { get; set; }
> > > >         public Guid CreatedBy { get; set; }
> > > >         public DateTimeOffset UpdatedDate { get; set; }
> > > >         public Guid UpdatedBy { get; set; }
> > > > 
> > > >         public Designation Designation { get; set; }
> > > > 
> > > >        //  I think this property is very important for teachers, 
> > > >       // whether we decide to keep it here or create a separate class to hold such data is a matter of discussion.
> > > >         public DateTimeOffset JoiningDate{ get; set; }
> > > > }
> > > > 
> > > > public enum Designation{
> > > >         Professor,
> > > >         Associate Professor,
> > > >         Lecturer,
> > > >         Instructor
> > > > }
> > > > ```
> > > 
> > > 
> > > Dear @devmanzur in case of having separated entity for employment information, then joining date and designation will moved there as a teacher/employees can have many designations and start and end dates during his/her stay in school even the joining date is same it will also move.
> > 
> > 
> > Dear @devmanzur I am agreed with @tajwal As per Standard Microsoft ERP Structured Separated entity for Employment information will be much better
> 
> Please remember that this only for schools, not colleges or universities - just schools until high school - so professors and such out of the scope of this project.

We might potentially want something like degree level, for eligibility to teach higher level courses such as AP/Dual Credit that are taught by High School teachers but require additional credentials. That might be better suited in a joined entity such as FacultyCredential though

**Comment by hassanhabib** [comment]
Hello everyone,
I've seen some great input in here, here's the consolidated model we should go with:
```csharp
public class Teacher : IAuditable
{
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Gender Gender { get; set; }
        public TeacherStatus Status {get; set;}
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
}

public enum Gender {
	Female,
	Male,
	Other
}

public enum TeacherStatus {
	Active,
	Retired,
	Terminated
}
```
Now, let's talk about assignments:

## Setup 

- Teacher Model Setup & Migrations with EF Core @eriadhami   Monday 12:00 AM - 11:59 PM PST

## Broker

- Teacher Broker Select By Id function @AgentEnder  by Tuesday 12:00 AM - 11:59 PM PST
- Teacher Broker Select All function @AgentEnder    by Tuesday 12:00 AM - 11:59 PM PST
- Teacher Broker Insert function @AgentEnder  by Tuesday 12:00 AM - 11:59 PM PST
- Teacher Broker Update function @AgentEnder  by Tuesday 12:00 AM - 11:59 PM PST
- Teacher Broker Delete function @AgentEnder  by Tuesday 12:00 AM - 11:59 PM PST

## Service

- Teacher Service Register function @a-urel  by Wednesday 12:00 AM - 11:59 PM PST
- Teacher Service Modify function @gauriramesh  by Wednesday 12:00 AM - 11:59 PM PST
- Teacher Service Retrieve by Id function @Akinnagbe by Wednesday 12:00 AM - 11:59 PM PST
- Teacher Service Retrieve All function @hiraldesai by Wednesday 12:00 AM - 11:59 PM PST
- Teacher Service Delete by Id function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- Teacher Controller Post endpoint @MCCshreyas  by Thursday 12:00 AM - 11:59 PM PST
- Teacher Controller Get by Id endpoint @tajwal by Thursday 12:00 AM - 11:59 PM PST
- Teacher Controller Get All endpoint @levirgon by Thursday 12:00 AM - 11:59 PM PST
- Teacher Controller Update endpoint @devmanzur by Thursday 12:00 AM - 11:59 PM PST
- Teacher Controller Delete endpoint @Mohamad-ali-8 by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- Teacher Post Acceptance Test @tobidub by Friday 12:00 AM - 11:59 PM PST
- Teacher Update Acceptance Test @HatemGamal by Friday 12:00 AM - 11:59 PM PST
- Teacher Get All Acceptance Test @AliCharper by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Broker and Controller - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an assignment this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.
```

**Comment by hassanhabib** [comment]
Closing this issue as all CRUD operations are completed.
