### ISSUE TITLE
CODE RUB - Retrieve All

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#344]
Hi everyone,
This week, I need everyone to remove any exception handling and their tests for any retrieve all methods that tries to handle `DbUpdateException` - all the possible exceptions that EF throws are just `SqlException` in this case - there's absolutely no way you would get a `DbUpdateException` when you do a RetrieveAll.

Please hit like on this post so I can assign next weeks tasks as well, thank you all.

**Comment by sasestil** [comment]
I think that this should also apply to RetrieveById methods. According to Microsoft documentation [DbUpdateException](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.dbupdateexception?view=entity-framework-6.2.0) is thrown by DbContext when the saving of changes to the database fails. RetrieveById methods does not make any changes to database.
