### ISSUE TITLE
Exam Fees Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#348]
![image](https://user-images.githubusercontent.com/1453985/114406088-19f95800-9b5c-11eb-836d-724b28839bb6.png)

Thank you all for your contributions, here's an overview of our ExamFee entity model this week:

```csharp
public class ExamFee {
    public Guid Id {get; set;}
    public Guid ExamId {get; set;}
    public Guid FeeId {get; set;}
    public ExamFeeStatus Status {get; set;}
    public DateTimeOffset CreatedDate {get; set;}
    public DateTimeOffset UpdatedDate {get; set;}
    public Guid CreatedBy {get; set;}
    public User CreatedByUser {get; set;}
    public Guid UpdatedBy {get; set;}
    public User UpdatedByUser {get; set;}
}

public enum ExamFeeStatus 
{
    Active,
    Inactive
}
```
Now, let's talk about ExamFees:

## Setup 

- ExamFee Model Setup & Migrations with EF Core @bilalmehrban Tuesday 12:00 AM - 11:59 PM PST

## Broker

- ExamFee Broker Select By Id function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- ExamFee Broker Select All function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- ExamFee Broker Insert function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- ExamFee Broker Delete function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- ExamFee Broker Update function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST

## Service

- ExamFee Service Add function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- ExamFee Service Retrieve by Id function @tajwal   by Wednesday 12:00 AM - 11:59 PM PST
- ExamFee Service Retrieve All function @stasnowak by Wednesday 12:00 AM - 11:59 PM PST
- ExamFee Service Delete by Id function @ZionLloyd05 by Wednesday 12:00 AM - 11:59 PM PST
- ExamFee Service Modify function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- ExamFee Controller Post endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- ExamFee Controller Get by Id endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- ExamFee Controller Get All endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- ExamFee Controller Delete endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- ExamFee Controller Put endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST

## Acceptance Tests

- ExamFee Post Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- ExamFee Get All Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- ExamFee Put Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- ExamFee Delete Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST

## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the ExamService, Exam and Exam Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an ExamFee this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by eriadhami** [comment]
@ZionLloyd05  @tajwal if you guys need help with your tasks I will be happy to help

**Comment by ZionLloyd05** [comment]
@eriadhami Thanks for offering to help out. 

Yes, I would need you to help out with my task if you're free to help. Thanks

**Comment by viralpandya** [comment]
I should be working on my assigned workitems today.

**Comment by tajwal** [comment]
> @ZionLloyd05 @tajwal if you guys need help with your tasks I will be happy to help

Yes, please I need your help this week.

**Comment by bilalmehrban** [comment]
> > @ZionLloyd05 @tajwal if you guys need help with your tasks I will be happy to help
> 
> Yes, please I need your help this week.

@tajwal How can I help? I have some free time. @eriadhami you can help @ZionLloyd05 , I will hell @tajwal. :)

**Comment by eriadhami** [comment]
@bilalmehrban many thanks but the tasks are finished.
