### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by MCCshreyas** [hassanhabib/OtripleS#35]
Hello all, 
Based upon till date conversation, I have created the class diagram. This will allow us to visualize the domain entities at a higher level and can help us to understand the corresponding entities. 
You can see the class diagram in the following link.
https://app.lucidchart.com/documents/view/428d3bdb-b3be-4480-8360-7bc5b5c24d89/0_0

Also am uploading the image here. 
![OtripleS](https://user-images.githubusercontent.com/17148381/86895889-c36d7200-c122-11ea-9d9e-4c1305fbf423.png)

**Comment by MCCshreyas** [comment]
@hassanhabib Can I get an email link of yours so that you can share this class diagram with the edit permissions so that you can add the latest fields and models going forward. Thanks.

**Comment by hassanhabib** [comment]
@MCCshreyas  please move this into this issue: https://github.com/hassanhabib/OtripleS/issues/33
