### ISSUE TITLE
Student Exam Fee Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#357]
![image](https://user-images.githubusercontent.com/1453985/114406088-19f95800-9b5c-11eb-836d-724b28839bb6.png)

Thank you all for your contributions, here's an overview of our StudentExamFee entity model this week:

```csharp
public class StudentExamFee {
    public Guid ExamFeeId {get; set;}
    public ExamFee ExamFee {get; set;}
    
    public Guid StudentId {get; set;}
    public Student Student {get; set;}
    
    public StudentExamFeeStatus Status {get; set;}
    public DateTimeOffset CreatedDate {get; set;}
    public DateTimeOffset UpdatedDate {get; set;}
    
    public Guid CreatedBy {get; set;}
    public User CreatedByUser {get; set;}
    
    public Guid UpdatedBy {get; set;}
    public User UpdatedByUser {get; set;}
}

public enum StudentExamFeeStatus 
{
    Pending,
    Paid,
    Deferred,
    Waived,
    Cancelled
}
```
Now, let's talk about StudentExamFees:

## Setup 

- StudentExamFee Model Setup & Migrations with EF Core @bilalmehrban Tuesday 12:00 AM - 11:59 PM PST

## Broker

- StudentExamFee Broker Select By Id function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- StudentExamFee Broker Select All function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- StudentExamFee Broker Insert function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- StudentExamFee Broker Delete function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST
- StudentExamFee Broker Update function @bilalmehrban by Tuesday 12:00 AM - 11:59 PM PST

## Service

- StudentExamFee Service Add function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST
- StudentExamFee Service Retrieve by Id function @tajwal   by Wednesday 12:00 AM - 11:59 PM PST
- StudentExamFee Service Retrieve All function @stasnowak by Wednesday 12:00 AM - 11:59 PM PST
- StudentExamFee Service Delete by Id function @ZionLloyd05 by Wednesday 12:00 AM - 11:59 PM PST
- StudentExamFee Service Modify function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- StudentExamFee Controller Post endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentExamFee Controller Get by Id endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentExamFee Controller Get All endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentExamFee Controller Delete endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST
- StudentExamFee Controller Put endpoint @viralpandya by Thursday 12:00 AM - 11:59 PM PST

## Acceptance Tests

- StudentExamFee Post Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- StudentExamFee Get All Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- StudentExamFee Put Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- StudentExamFee Delete Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST

## Contribution Rules:
1. Make sure you follow the coding guidelines in the [C# Coding Standard](https://github.com/hassanhabib/CSharpCodingStandard)
2. This project follows [The Standard](https://github.com/hassanhabib/The-Standard) - an engineering guideline to incorporate SOLID principles along with code readability and engineering experience as first class citizens.
3. Please hit the like button on this post so I can consider you for next sprint.

**Comment by bilalmehrban** [comment]
@hassanhabib 
I have added the below as PK to the above model.
`public Guid Id {get; set;}`

**Comment by hassanhabib** [comment]
@bilalmehrban perfect! thank you - I appreciate your effort.

**Comment by hassanhabib** [comment]
Holding off this week until we resolve the `id` issue.
@viralpandya  keep me posted on this please.

**Comment by viralpandya** [comment]
Its a huge change. Yesterday, resolved that issue and fixed errors related to Id. Tonight, I should be able to create PR for the same.

**Comment by eriadhami** [comment]
I can help. Just tell me what you want me to do

**Comment by viralpandya** [comment]
Thank you, @eriadhami! Once, these changes are merged in, I should ask you for help (if I am running out of time). Thank you so much for the kind offer. Appreciate team's great work!
