### ISSUE TITLE
Student Registration Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#381]
This upcoming week, we will be working on the Student Registration Model
This model is just a many to many glue entity to reference a student by id and a registration by id as follows:

```csharp
public class StudentRegistration 
{
    public Guid StudentId {get; set;}
    public Guid RegisterationId {get; set;}
}
```

Please hit the like button here so I can assign work to you next week.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our StudentRegistration entity model this week:

```csharp
 public class StudentRegistration
    {
        public Guid StudentId {get; set;}
        public Student Student {get; set;}
        
        public Guid RegistrationId {get; set;}
        public Registration Registration {get; set;}
    }
```
Now, let's talk about StudentRegistration :

## Setup 

- StudentRegistration Model Setup & Migrations with EF Core @eriadhami  Tuesday 12:00 AM - 11:59 PM PST

## Broker

- StudentRegistration Broker Select By Id function @eriadhami  by Tuesday 12:00 AM - 11:59 PM PST
- StudentRegistration Broker Select All function @eriadhami  by Tuesday 12:00 AM - 11:59 PM PST
- StudentRegistration Broker Insert function @eriadhami  by Tuesday 12:00 AM - 11:59 PM PST
- StudentRegistration Broker Delete function @eriadhami  by Tuesday 12:00 AM - 11:59 PM PST

## Service

- StudentRegistration Service Add function @stasnowak  by Wednesday 12:00 AM - 11:59 PM PST
- StudentRegistration Service Retrieve by Id function @bilalmehrban by Wednesday 12:00 AM - 11:59 PM PST
- StudentRegistration Service Retrieve All function @ZionLloyd05 by Wednesday 12:00 AM - 11:59 PM PST
- StudentRegistration Service Delete by Id function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- StudentRegistration Controller Post endpoint @todoca by Thursday 12:00 AM - 11:59 PM PST
- StudentRegistration Controller Get by Id endpoint @todoca by Thursday 12:00 AM - 11:59 PM PST
- StudentRegistration Controller Get All endpoint @todoca by Thursday 12:00 AM - 11:59 PM PST
- StudentRegistration Controller Delete endpoint @todoca by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- StudentRegistration Post Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- StudentRegistration Get All Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST
- StudentRegistration Delete Acceptance Test @viralpandya by Friday 12:00 AM - 11:59 PM PST

## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the AssignmentService, Assignment and Assignment Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an StudentRegistration task this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on Teams and I will be sure to response within 2 - 4 hours max.

**Comment by hassanhabib** [comment]
@todca are you gonna be able to finalize controllers?
@eriadhami I might need you to take care of the controllers if @todca isn't avaialb.e

**Comment by todoca** [comment]
hi my dear friend @hassanhabib, honestly, I need help to upload the code to github, it is my first time in collaborative mode, I would greatly appreciate if you could explain to me a little what I should do. Thanks in advance.

**Comment by todoca** [comment]
I think I did it! please give me your comments and thanks for the opportunity to collaborate.

**Comment by stasnowak** [comment]
@todoca Hay i do not see a pull request from your side. If your code is local you need to commit and push it to your fork of 
OtripleS. After that you will be ask inside visual studio to create a pull request from commited stuff (you will be redirected to github.com to complete). I included two pictures and hope this helps. You also need to make sure that your branch is up to date with the current master of hassanhabib/OtripleS version.

![10](https://user-images.githubusercontent.com/74690088/120277827-d944d200-c2b4-11eb-84aa-1b54a02fb59c.PNG)
![11](https://user-images.githubusercontent.com/74690088/120278037-14df9c00-c2b5-11eb-8599-91b7ae7e7d27.PNG)

**Comment by bilalmehrban** [comment]
@todoca I have some free time I can explain you how you can make PR, let me know when you are avialable we can have call on teams than I can show you can do it.

**Comment by todoca** [comment]
Hi my dear friends, @stasnowak and @bilalmehrban, I think I already did, considering your help.
I attach the images of what I do. Thanks for the support, and if there are any additional steps, please let me know.

![fork](https://user-images.githubusercontent.com/69520003/120305763-0037df80-c286-11eb-9a8d-ec6bca09af11.png)
![pullrequest](https://user-images.githubusercontent.com/69520003/120306064-53aa2d80-c286-11eb-998f-c7a27c3ade2c.png)

**Comment by bilalmehrban** [comment]
@todoca great work buddy, I can see your Pull Request.

**Comment by viralpandya** [comment]
@hassanhabib : I will complete acceptance tests by tonight/tomorrow.
