### ISSUE TITLE
In consistence property naming in *.Exceptions.cs

### ISSUE THREAD

**Issue by babula38** [hassanhabib/OtripleS#391]
I noticed there is a inconsistent naming of the property in service classes. [StudentService.ReturningQueryableStudentFunction](https://github.com/hassanhabib/OtripleS/blob/2cfe7d9f509013bda8e5a2d73e48006c847c0f13/OtripleS.Web.Api/Services/Students/StudentService.Exceptions.cs#L20).
Vs [StudentExamService,ReturningStudentExamsFunction();](https://github.com/hassanhabib/OtripleS/blob/2cfe7d9f509013bda8e5a2d73e48006c847c0f13/OtripleS.Web.Api/Services/StudentExams/StudentExamService.Exceptions.cs#L19)

Could you let me know which is the standard, if needed then I could do the refactor

**Comment by hassanhabib** [comment]
@babula38 the second for sure.

**Comment by babula38** [comment]
Shalli work on this?

**Comment by hassanhabib** [comment]
@babula38 go for it.
