### ISSUE TITLE
Service Methods RetrievexxxByIdAsync(Guid id) should test for retrieved id to be same as parameter id

### ISSUE THREAD

**Issue by jayendusharma** [hassanhabib/OtripleS#414]
Should there be a unit test to ensure that within service methods which retrieve from Db via a Guid Id, the retrieved object's id and passed parameter id should be same?

E.g.  One can modify this code

```

 public ValueTask<Student> RetrieveStudentByIdAsync(Guid studentId) =>
        TryCatch(async () =>
        {
            ValidateStudentId(studentId);
            Student storageStudent = await this.storageBroker.SelectStudentByIdAsync(studentId);
            ValidateStorageStudent(storageStudent, studentId);

            return storageStudent;
        });
```

To 

```

 public ValueTask<Student> RetrieveStudentByIdAsync(Guid studentId) =>
        TryCatch(async () =>
        {
            ValidateStudentId(studentId);
            Student storageStudent = await this.storageBroker.SelectStudentByIdAsync(studentId);
        
             if (storageStudent is not null)
                storageStudent.Id = Guid.NewGuid();

            ValidateStorageStudent(storageStudent, studentId);     

            return storageStudent;
        });
```
And all Unit tests will still pass

**Comment by hassanhabib** [comment]
There should be. but that's part of a new pattern I'm still working on that I call DuplexValidations which means everything coming from storage has to also be valid.
For instance, if we are pulling a Student from storage with an `UpdatedDate` that is less than `CreatedDate` then we should throw a `CorruptStudentDataException` - same thing in your case here - 100%.
Might roll out that change soon - stay posted.
