### ISSUE TITLE
Discuss Classroom Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#47]
Hi everyone!
In this issue, we will be discussing the Classroom model, here's a draft model for discussion:

```csharp

using System;
					
public class Classroom {
	public Guid Id {get; set;}
	public string Name {get; set;}
	public string Location {get; set;}
	public ClassroomStatus Status {get; set;}
	public DateTimeOffset CreatedDate {get; set;}
	public DateTimeOffset UpdatedDate {get; set;}
	public Guid CreatedBy {get; set;}
	public Guid UpdatedBy {get; set;}
}

public enum ClassroomStatus {
	Active,
	Inactive
}

```

I think there's much more to add to a classroom than just the aforementioned, I'm also not sure the current statuses are inclusive - let's discuss :)

**Comment by mykjar** [comment]
I think there should be Capacity (seating places?) property there.
Additionally maybe some information on classroom being capable of audio / video / any-other-tech ?

**Comment by hassanhabib** [comment]
> I think there should be Capacity (seating places?) property there.
> Additionally maybe some information on classroom being capable of audio / video / any-other-tech ?

@mykjar very good point - keep the good thoughts coming.

**Comment by mykjar** [comment]
I would say that it is worth changing _Location_ property from string to class with corresponding properties (_Building, Floor, ect._) as there might be multi building / multi floor  + it might will be necessity if there would be _scheduling / booking / availability_ service in future.

**Comment by chaouanabil** [comment]
You can add ClassromeType:  auditorium , Laboratory ...

**Comment by hassanhabib** [comment]
> I would say that it is worth changing _Location_ property from string to class with corresponding properties (_Building, Floor, ect._) as there might be multi building / multi floor + it might will be necessity if there would be _scheduling / booking / availability_ service in future.

@mykjar that means it would be a related entity, I agree - we should put it in it's own entity, good point.

**Comment by hassanhabib** [comment]
> You can add ClassromType: auditorium , Laboratory ...

@chaouanabil would that be an enum or just an open string?

**Comment by mykjar** [comment]
Simple addition - Accessibility property? I am not sure if this should be just a flag or a list of items. Most likely list of predefined entities (_Type, Description, ect._).

**Comment by a-urel** [comment]
> > You can add ClassromType: auditorium , Laboratory ...
> 
> @chaouanabil would that be an enum or just an open string?

I think _string_ is a better choice. We can provide a predefined (localizable) list without forcing to use them.

**Comment by tajwal** [comment]
> > You can add ClassromType: auditorium , Laboratory ...
> 
> @chaouanabil would that be an enum or just an open string?

@hassanhabib  & @chaouanabil , I was thinking that ClassroomType is needed, now if classroom types are more and dynamic then I think it would be better to have a table for ClassroomTypes(Id, Description) with some more property may be added in future, but if its fixed list and not changing then enum would be enough.

**Comment by mykjar** [comment]
> > > You can add ClassromType: auditorium , Laboratory ...
> > 
> > 
> > @chaouanabil would that be an enum or just an open string?
> 
> @hassanhabib & @chaouanabil , I was thinking that ClassroomType is needed, now if classroom types are more and dynamic then I think it would be better to have a table for ClassroomTypes(Id, Description) with some more property may be added in future, but if its fixed list and not changing then enum would be enough.

I would second this. Table is better. This kind of data will be change per system use case. Predefined enum is not a best choice.

**Comment by chaouanabil** [comment]
@hassanhabib  yes, I think enum is better (specialy that i m thinking we could add a relationship between course or couseSession and ClassroomType. i mean some couses should be given in certains ClassroomType ). And about enums, do you have docs giving some best practices to display enums as string (with localization) when querying it.

**Comment by tajwal** [comment]
> > > > You can add ClassromType: auditorium , Laboratory ...
> > > 
> > > 
> > > @chaouanabil would that be an enum or just an open string?
> > 
> > 
> > @hassanhabib & @chaouanabil , I was thinking that ClassroomType is needed, now if classroom types are more and dynamic then I think it would be better to have a table for ClassroomTypes(Id, Description) with some more property may be added in future, but if its fixed list and not changing then enum would be enough.
> 
> I would second this. Table is better. This kind of data will be change per system use case. Predefined enum is not a best choice.

@mykjar I don't have school system experience but I was part of hostel management system where we added separate table for roomtypes and beside having branch's, buildings, floors, there were sections inside each floor and rooms where added to section based on its type, I not sure if is this possible in school system or not, @a-urel may have information about this.

**Comment by chaouanabil** [comment]
@tajwal @mykjar, a table also a good choice. i prefere enum over string property and table (Entity) over enum.

**Comment by a-urel** [comment]
I think over-normalization is not a good practice. When all we need is to prevent incorrect entries, a list of suggestions (a predefined list and/or most-recently-used items in a combo-box, not enum) is enough.

**Comment by mykjar** [comment]
> I think over-normalization is not a good practice. When all we need is to prevent incorrect entries, a list of suggestions (a predefined list and/or most-recently-used items in a combo-box, not enum) is enough.

So enum with some generic, out-of-the-box, options + possibility to enter value freely?

**Comment by chaouanabil** [comment]
@a-urel if this information is used just in this entity and it hasn't other business rules  (as i mentioned , some courses could requiee certain classroomType and this is it give us a business rule when we schedulea couse session in a classroom ). another problem with this solution is where to stock this list of options.

**Comment by a-urel** [comment]
IMO we shouldn't create an entity if its properties are just _id_ and _name_. Especially when this name must be localized. 
In this case we can simply provide a combo-box with a localized list (eg. from `.resx`) of items, and allow end-user to enter a value which is not listed. This approach allows us to prevent incorrect entries (w/ auto-complete), as well as provides enough flexibility.

**Comment by hassanhabib** [comment]
> IMO we shouldn't create an entity if its properties are just _id_ and _name_. Especially when this name must be localized.
> In this case we can simply provide a combo-box with a localized list (eg. from `.resx`) of items, and allow end-user to enter a value which is not listed. This approach allows us to prevent incorrect entries (w/ auto-complete), as well as provides enough flexibility.

@a-urel I agree - but I think the `Classroom` model should have more than that - what are your thoughts on what needs to be in a `Classroom` model?

**Comment by hassanhabib** [comment]
> > > You can add ClassromType: auditorium , Laboratory ...
> > 
> > 
> > @chaouanabil would that be an enum or just an open string?
> 
> @hassanhabib & @chaouanabil , I was thinking that ClassroomType is needed, now if classroom types are more and dynamic then I think it would be better to have a table for ClassroomTypes(Id, Description) with some more property may be added in future, but if its fixed list and not changing then enum would be enough.

@tajwal  that's a good point - I agree.

**Comment by JaAfghan** [comment]
> > > You can add ClassromType: auditorium , Laboratory ...
> > 
> > 
> > @chaouanabil would that be an enum or just an open string?
> 
> @hassanhabib & @chaouanabil , I was thinking that ClassroomType is needed, now if classroom types are more and dynamic then I think it would be better to have a table for ClassroomTypes(Id, Description) with some more property may be added in future, but if its fixed list and not changing then enum would be enough

> > > You can add ClassromType: auditorium , Laboratory ...
> > 
> > 
> > @chaouanabil would that be an enum or just an open string?
> 
> @hassanhabib & @chaouanabil , I was thinking that ClassroomType is needed, now if classroom types are more and dynamic then I think it would be better to have a table for ClassroomTypes(Id, Description) with some more property may be added in future, but if its fixed list and not changing then enum would be enough.

**Comment by JaAfghan** [comment]
Mr.@hassanhabib  I think it would be better to used table for ClassroomType

**Comment by hassanhabib** [comment]
> Mr.@hassanhabib  I think it would be better to used table for ClassroomType

@JaAfghan it makes it definitely more extendable to make the types as external entity. I agree.

**Comment by HatemGamal** [comment]
I think there are two kinds of status we should consider, one represents whether the room is active or not, meaning the room can't hold a class yet for cases such as room maintenance, refurbishment, or under construction. The other cases define if the room is free or occupied.

**Comment by eriadhami** [comment]
> The other status defines if the room is free or occupied.

To define if the classroom is free or occupied, i think will be better to have kind of timetable for each classroom which will include time and subject. Eg classroom 2B on  9-11 Math, 14-17 Biology....

**Comment by hassanhabib** [comment]
> > The other status defines if the room is free or occupied.
> 
> To define if the classroom is free or occupied, i think will be better to have kind of timetable for each classroom which will include time and subject. Eg classroom 2B on Monday at 9:00-11:30 Math, 14:00-17:00 Biology....

@eriadhami that would be a related entity, we would call it something like `ClassroomSchedule` - but definitely something to consider.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our Classroom entity model and the assignments this week:

```csharp

using System;
					
public class Classroom {
	public Guid Id {get; set;}
	public string Name {get; set;}
	public string Location {get; set;}
	public ClassroomStatus Status {get; set;}
	public DateTimeOffset CreatedDate {get; set;}
	public DateTimeOffset UpdatedDate {get; set;}
	public Guid CreatedBy {get; set;}
	public Guid UpdatedBy {get; set;}
}

public enum ClassroomStatus {
         Available,
         Busy,
         InMaintenance,
         Closed
}

```
Now, let's talk about assignments:

## Setup 

- Classroom Model Setup & Migrations with EF Core @hiraldesai Monday 12:00 AM - 11:59 PM PST 

## Broker

- Classroom Broker Select By Id function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST
- Classroom Broker Select All function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST 
- Classroom Broker Insert function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST 
- Classroom Broker Update function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST
- Classroom Broker Delete function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST 

## Service

- Classroom Service Add function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- Classroom Service Modify function @tobidub   by Wednesday 12:00 AM - 11:59 PM PST
- Classroom Service Retrieve by Id function @gauriramesh  by Wednesday 12:00 AM - 11:59 PM PST
- Classroom Service Retrieve All function @JaAfghan  by Wednesday 12:00 AM - 11:59 PM PST
- Classroom Service Delete by Id function @eriadhami  by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- Classroom Controller Post endpoint @AgentEnder  by Thursday 12:00 AM - 11:59 PM PST 
- Classroom Controller Get by Id endpoint @devmanzur  by Thursday 12:00 AM - 11:59 PM PST 
- Classroom Controller Get All endpoint @Mohamad-ali-8 by Thursday 12:00 AM - 11:59 PM PST
- Classroom Controller Update endpoint @chaouanabil by Thursday 12:00 AM - 11:59 PM PST
- Classroom Controller Delete endpoint @devmanzur   by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- Classroom Post Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST
- Classroom Update Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST
- Classroom Get All Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an assignment this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by AgentEnder** [comment]
@hassanhabib  Ended up not quite getting to this today, will get it done asap tomorrow morning if still available

**Comment by hassanhabib** [comment]
Closing this issue in favor of this commit: https://github.com/hassanhabib/OtripleS/commit/118977934c1509c2e7a6f8050d88b88ed599569d
