### ISSUE TITLE
CODE RUB: Code Cleanup

### ISSUE THREAD

**Issue by ShriHumrudha** [hassanhabib/OtripleS#514]
A new line is required between 138 and 139.

_Originally posted by @ShriHumrudha in https://github.com/hassanhabib/OtripleS/pull/511#r730339375_

**Comment by arafat-pro** [comment]
Hello @ShriHumrudha can you please tell me what does it mean by "Code Rub" here?

**Comment by arafat-pro** [comment]
> Hello @ShriHumrudha can you please tell me what does it mean by "Code Rub" here?

I've found my answer here: [https://www.linkedin.com/pulse/code-rub-hassan-rezk-habib/](url)

**Comment by ShriHumrudha** [comment]
@arafat-pro Unable to find the code for cleanup. So I will close this PR.

In general, CODE RUB means to make our code better in various terms - Running Code Cleanup, Upgrading Packages, Meeting the standard.
