### ISSUE TITLE
CODE RUB: Change Model Name from InvalidExamInputException to InvalidExamException

### ISSUE THREAD

**Issue by ShriHumrudha** [hassanhabib/OtripleS#556]

**Comment by rcruzfreelance** [comment]
this seems to have already been done

![image](https://user-images.githubusercontent.com/53588704/141233946-0141bdb3-1cfa-4e1e-a6d5-fa5b930b58f7.png)

**Comment by ShriHumrudha** [comment]
Closing the issue as it is resolved in another thread.
