### ISSUE TITLE
CODE RUB: Teacher Contact SameExceptionAs correction

### ISSUE THREAD

**Issue by ShriHumrudha** [hassanhabib/OtripleS#600]

**Comment by rcruzfreelance** [comment]
I'm noticing that this also needs to localize dependency exceptions as well in order for the test to pass. Can I be assigned for this?

**Comment by rcruzfreelance** [comment]
also needs to localize service exception as well

**Comment by ShriHumrudha** [comment]
Address one change in one PR. Feel free to pick localization even though there is no task listed.
