### ISSUE TITLE
CODE RUB: Teacher SameExceptionAs correction

### ISSUE THREAD

**Issue by ShriHumrudha** [hassanhabib/OtripleS#601]

**Comment by rcruzfreelance** [comment]
Does this by any chance need the logic to compare the inner exception data?

**Comment by ShriHumrudha** [comment]
Yes, we should. If the new validation standard is not implemented across all the operations, then we need to wait to modify it.

**Comment by rcruzfreelance** [comment]
I realized that this is already in the correct standard

![image](https://user-images.githubusercontent.com/53588704/141887932-296b497f-5e47-4afd-ab7e-aa4262402da3.png)

**Comment by ShriHumrudha** [comment]
Resolving the issue as it is taken care.
