### ISSUE TITLE
Discuss Assignment Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#62]
Hi Everyone,
In this issue, we will be discussing the Assignment model, here's a draft idea of a model:

```csharp

    class Assignment
    {
        public Guid Id { get; set; }
        public string Label { get; set; }
        public string Content { get; set; }
        public AssignmentStatus Status { get; set; }
        public Guid CourseId { get; set; }
        public Course Course { get; set; }
        public DateTimeOffset Deadline { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }

    enum AssignmentStatus
    {
        Active,
        Closed
    }

```

**Comment by tajwal** [comment]
Assignment can have  AssigmentType if its minor,major or any other type.

**Comment by JaAfghan** [comment]
Assignment can have submission type which can be Submitted us a hard copy or Submitted online .

**Comment by syedib** [comment]
Assignment Submission Status like below

**Submitted** - On Successfully submission within the deadline
**Not Submitted**  - Yet to be submitted within the deadline
**Overdue** - Yet to be submitted after the deadline
**Correction Needed** - If any correction needed

Teacher may need to enter any feedback about the assignment so we should have a field like **Comments**

**Comment by hassanhabib** [comment]
> Assignment Submission Status like below
> 
> **Submitted** - On Successfully submission within the deadline
> **Not Submitted** - Yet to be submitted within the deadline
> **Overdue** - Not Yet submitted after the deadline
> **Correction Needed** - If any correction needed
> 
> Teacher may need to enter any feedback about the assignment so we should have a field like **Comments**

@syedib I like that - good thoughts.
I wonder if there would be any other statuses for an assignment?

**Comment by AgentEnder** [comment]
If this model is for the actual assignment, those statuses do not make a lot of sense. Those would belong to a different entity, perhaps 'submission' or something.  Relations would look something like: Course 1:M Assignment 1:M Submission M:1 Student.

Students would 'submit' their assignments, but the assignment itself is the same entity for each student.

**Comment by syedib** [comment]
> > Assignment Submission Status like below
> > **Submitted** - On Successfully submission within the deadline
> > **Not Submitted** - Yet to be submitted within the deadline
> > **Overdue** - Not Yet submitted after the deadline
> > **Correction Needed** - If any correction needed
> > Teacher may need to enter any feedback about the assignment so we should have a field like **Comments**
> 
> @syedib I like that - good thoughts.
> I wonder if there would be any other statuses for an assignment?

in this case we can make submission status as configurable, as @AgentEnder Mentioned we should have a separate entity for Assignment Submission,

**Comment by hassanhabib** [comment]
> If this model is for the actual assignment, those statuses do not make a lot of sense. Those would belong to a different entity, perhaps 'submission' or something. Relations would look something like: Course 1:M Assignment 1:M Submission M:1 Student.
> 
> Students would 'submit' their assignments, but the assignment itself is the same entity for each student. We definitely need both, and need to keep a clear picture as to what entity we are working on.

@AgentEnder that's a pretty good point.
But even without the submission entity, the assignment might be just about the actual content of the assignment. not the submission of the student for the assignment right?
For instance, an assignment can be active once a teacher posts it online for students to start working on it.
It then becomes inactive, or complete once the period of time is done where students have to submit their homework.
So there is `AssignmentSubmission` that has the studentId and the AssignmentId and all that.
And there's the `Assignment` which links to a `Course` maybe a `Teacher`? something like that.
Do you think it still doesn't need a status? I can see why it may or may not have statuses in it.

**Comment by AgentEnder** [comment]
I think status makes sense, but listing things like teacher feedback, late vs submitted etc do not belong on this one

**Comment by HatemGamal** [comment]
I think this entity should be related only to teachers so that they can assign homework/assignments to their students.
And for students to submit their homework we need to create a new entity called maybe AssignmentSubmissions which should have relations with Student, Teacher, and Assignment entities.

In this model, we can add the score percentage, meaning how much the score of this assignment will affect the final score.

**Comment by hassanhabib** [comment]
> I think this entity should be related only to teachers so that they can assign homework/assignments to their students.
> And for students to submit their homework we need to create a new entity called maybe AssignmentSubmissions which should have relations with Student, Teacher, and Assignment entities.
> 
> In this model, we can add the score percentage, meaning how much the score of this assignment will affect the final score.

@HatemGamal  good point, so a teacher and a course - I agree.

**Comment by eriadhami** [comment]
Assignment model can have also a property Attach. The Teacher creating the Assignment maybe will need something to Attach. I would suggest something like: `public string Attach { get; set; }`

**Comment by a-urel** [comment]
I think `Course` model is not a _good_ master record for the `Assignment` model.
We need new entity like
```csharp
public class SemesterCourse
{
    public Guid Id { get; set; }
    public Semester { get; set; } // todo
    public Course Course { get; set; }
    public Teacher Teacher { get; set; }
    public Classroom Classroom { get; set; }
    public SemesterCourseStatus Status { get; set; }
}

public enum SemesterCourseStatus
{
    Draft,
    Active,
    Canceled,
    Closed
}
```
Not `Course`, but `SemesterCourse` entity should contain the `Assignments` list, `Quizzes` list, etc.

**Comment by hassanhabib** [comment]
> I think `Course` model is not a _good_ master record for the `Assignment` model.
> We need a _new_ entity like
> 
> ```cs
> public class SemesterCourse
> {
>     public Guid Id { get; set; }
>     public Semester { get; set; } // todo
>     public Course Course { get; set; }
>     public Teacher Teacher { get; set; }
>     public Classroom Classroom { get; set; }
>     public SemesterCourseStatus Status { get; set; }
> }
> 
> public enum SemesterCourseStatus
> {
>     Draft,
>     Active,
>     Canceled,
>     Closed
> }
> ```
> 
> Not `Course`, but `SemesterCourse` entity should contain the `Assignments` list, `Quizzes` list, etc.

@a-urel that's a good point.
In this case we will build the `Assignment` entity without the course reference, but we should add a Teacher reference then later with the `SemesterCourse` we could potential link the two entities together.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our Assignment entity model and the assignments this week:

```csharp

using System;
					
 class Assignment
    {
        public Guid Id { get; set; }
        public string Label { get; set; }
        public string Content { get; set; }
        public AssignmentStatus Status { get; set; }
        public DateTimeOffset Deadline { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }

    enum AssignmentStatus
    {
        Active,
        Closed
    }

```
**We should followup on this model by building a relationship between it and the `SemesterCourse` as @a-urel indicated.**

Now, let's talk about assignments:

## Setup 

- Assignment Model Setup & Migrations with EF Core @viralpandya Monday 12:00 AM - 11:59 PM PST  [done]

## Broker

- Assignment Broker Select By Id function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST [done]
- Assignment Broker Select All function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST  [done]
- Assignment Broker Insert function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST [done]
- Assignment Broker Update function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST [done]
- Assignment Broker Delete function @HatemGamal by Tuesday 12:00 AM - 11:59 PM PST [done]

## Service

- Assignment Service Add function @eriadhami by Wednesday 12:00 AM - 11:59 PM PST [done]
- Assignment Service Modify function @tobidub   by Wednesday 12:00 AM - 11:59 PM PST
- Assignment Service Retrieve by Id function @AgentEnder  by Wednesday 12:00 AM - 11:59 PM PST
- Assignment Service Retrieve All function @syedib   by Wednesday 12:00 AM - 11:59 PM PST
- Assignment Service Delete by Id function @hiraldesai   by Wednesday 12:00 AM - 11:59 PM PST [done]

## Controller

- Assignment Controller Post endpoint @Mohamad-ali-8  by Thursday 12:00 AM - 11:59 PM PST 
- Assignment Controller Get by Id endpoint @Mohamad-ali-8  by Thursday 12:00 AM - 11:59 PM PST 
- Assignment Controller Get All endpoint @Mohamad-ali-8 by Thursday 12:00 AM - 11:59 PM PST
- Assignment Controller Update endpoint @Mohamad-ali-8 by Thursday 12:00 AM - 11:59 PM PST
- Assignment Controller Delete endpoint @Mohamad-ali-8   by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- Assignment Post Acceptance Test @devmanzur  by Friday 12:00 AM - 11:59 PM PST
- Assignment Update Acceptance Test @devmanzur by Friday 12:00 AM - 11:59 PM PST
- Assignment Get All Acceptance Test @devmanzur by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an assignment this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by devmanzur** [comment]
my acceptance tests are ready. waiting for related service and endpoints to be merged.

**Comment by hassanhabib** [comment]
Closing this issue in favor of this commit: https://github.com/hassanhabib/OtripleS/commit/465d16f0997af58da2209bb46df9d0cd49204a3b
