### ISSUE TITLE
CODE RUB: Teacher Attachment Filler method order

### ISSUE THREAD

**Issue by ShriHumrudha** [hassanhabib/OtripleS#628]

**Comment by arafat-pro** [comment]
@hassanhabib 
how to deal with this issue and others alike?

**Comment by hassanhabib** [comment]
![image](https://user-images.githubusercontent.com/1453985/139641717-94b17009-d462-4386-a852-a736d99a700a.png)

@arafat-pro all you gotta do is move the Filler method in any root test file to the very bottom of the list. just like the example in the image above.

**Comment by arafat-pro** [comment]
> 
> @arafat-pro all you gotta do is move the Filler method in any root test file to the very bottom of the list. just like the example in the image above.
>
I've given it a try following the above guidance and created a PR as #736

**Comment by ShriHumrudha** [comment]
Closed via #736
