### ISSUE TITLE
CODE RUB: Remove Storage Validations from Contacts Retrieve All

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#645]

**Comment by hassanhabib** [comment]
Assigning this to @SallyDeveloper

**Comment by hassanhabib** [comment]
@SallyDeveloper  here's a good example of this effort:
https://github.com/hassanhabib/OtripleS/pull/737

**Comment by SallyDeveloper** [comment]
This issue is already done!

**Comment by SallyDeveloper** [comment]
This issue is already addressed.
