### ISSUE TITLE
Issue with Unit And Acceptance Projects

### ISSUE THREAD

**Issue by Mohamad-ali-8** [hassanhabib/OtripleS#7]
![image](https://user-images.githubusercontent.com/66647857/86215699-3ffece80-bbc0-11ea-8e40-1f708cb7f631.png)

**Comment by eriadhami** [comment]
Me too
<img width="1417" alt="Screenshot 2020-07-01 at 1 19 24 PM" src="https://user-images.githubusercontent.com/45641379/86238319-93abf080-bb9d-11ea-8b0f-a766f44c40fc.png">

**Comment by eriadhami** [comment]
Edit OtripleS.Web.Api.Tests.Unit.csproj and OtripleS.Web.Api.Tests.Acceptance.csproj to targetframework netcoreapp3.1

**Comment by Driedas** [comment]
same here, installation of the latest .net 5 preview SDK did not help...

**Comment by eriadhami** [comment]
> same here, installation of the latest .net 5 preview SDK did not help...

Installation of the latest .net 5 preview SDK did not help because the main project OtripleS.Web.Api is netcoreapp3.1 so the only way is to change the OtripleS.Web.Api.Tests.Unit.csproj and OtripleS.Web.Api.Tests.Acceptance.csproj targetframework to netcoreapp3.1

**Comment by Driedas** [comment]
thanks, that got it working, have struggled with that yesterday for about two hours, how simple... D'oh :-)

**Comment by hassanhabib** [comment]
I think this issue is fixed now - all projects target the right framework.
