### ISSUE TITLE
Discuss Semester Course Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#78]
Per @a-urel  suggestion - this model is a sub entity off of the `Course` model and it's very specific to a particular semester, teacher and a course as follows:

```csharp 
public class SemesterCourse
{
    public Guid Id { get; set; }
    public Guid CourseId {get; set;}
    public Course Course { get; set; }
    public Guid TeacherId {get; set;}
    public Teacher Teacher { get; set; }
    public Guid ClassroomId {get; set;}
    public Classroom Classroom { get; set; }
    public SemesterCourseStatus Status { get; set; }
}

public enum SemesterCourseStatus
{
    Draft,
    Active,
    Canceled,
    Closed
}

```

Let's discuss the details.

**Comment by AgentEnder** [comment]
This is probably where the ICollection<Student> Students should go to link students to their class schedule

**Comment by AgentEnder** [comment]
Also would need a days property for what days the class occurs  (think MWF vs TR classes in colleges, there are similar possibilities in K12) as well as a Time property for startTime and either a float or second Time property to represent duration/end time

**Comment by a-urel** [comment]
> This is probably where the `ICollection<Student> Students` should go to link students to their class schedule

There's a many-to-many relation between `SemesterCourse` and `Student`, but I think a connection table like `StudentCourseRegistration` (instead of navigation properties like `ICollection<Student> Students`) would be a better design. `StudentCourseRegistration` entity should contain student's _score_, status (_passed/failed_), etc.

**Comment by AgentEnder** [comment]
Agreed, that makes more sense

**Comment by hassanhabib** [comment]
@a-urel a semester course is a many to many relationship with a student right?
A middle "glue" entity might be required like a `StudentSemesterCourses` to combine a composite key of a student Id and a semester Id into the same entity.
In which case a student model would have rather `IEnumerable<StudentSemesterCourse>` and a course would have similar `IEnumerable<StudentSemesterCourse>` in both entities.

Thoughts?

**Comment by a-urel** [comment]
@hassanhabib yes, exactly.

**Comment by eriadhami** [comment]
Do we need to implement the `IAuditable` on this model?

**Comment by a-urel** [comment]
> Do we need to implement the `IAuditable` on this model?

Yes, I think so.

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our SemesterCourse entity model and the SemesterCourses this week:

```csharp

using System;
					
    public class SemesterCourse : IAuditable
    {
        public Guid Id { get; set; }
        public DateTimeOffset StartDate {get; set;}
        public DateTimeOffset EndDate {get; set;}
        public SemesterCourseStatus Status { get; set; }
        public Guid CourseId {get; set;}
        public Course Course { get; set; }
        public Guid TeacherId {get; set;}
        public Teacher Teacher { get; set; }
        public Guid ClassroomId {get; set;}
        public Classroom Classroom { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
    }

    public enum SemesterCourseStatus
    {
        Pending,
        Started,
        Ended,
        Cancelled
    }

```
Now, let's talk about SemesterCourses:

## Setup 

- SemesterCourse Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST

## Broker

- SemesterCourse Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- SemesterCourse Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST 
- SemesterCourse Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- SemesterCourse Broker Update function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- SemesterCourse Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST

## Service

- SemesterCourse Service Add function @AgentEnder by Wednesday 12:00 AM - 11:59 PM PST
- SemesterCourse Service Modify function @hiraldesai by Wednesday 12:00 AM - 11:59 PM PST
- SemesterCourse Service Retrieve by Id function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
- SemesterCourse Service Retrieve All function @tajwal by Wednesday 12:00 AM - 11:59 PM PST
- SemesterCourse Service Delete by Id function @devmanzur by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- SemesterCourse Controller Post endpoint @eriadhami   by Thursday 12:00 AM - 11:59 PM PST 
- SemesterCourse Controller Get by Id endpoint @eriadhami   by Thursday 12:00 AM - 11:59 PM PST 
- SemesterCourse Controller Get All endpoint @eriadhami  by Thursday 12:00 AM - 11:59 PM PST
- SemesterCourse Controller Update endpoint @eriadhami  by Thursday 12:00 AM - 11:59 PM PST
- SemesterCourse Controller Delete endpoint @eriadhami   by Thursday 12:00 AM - 11:59 PM PST


## Acceptance Tests

- SemesterCourse Post Acceptance Test @HatemGamal by Friday 12:00 AM - 11:59 PM PST
- SemesterCourse Update Acceptance Test @HatemGamal by Friday 12:00 AM - 11:59 PM PST
- SemesterCourse Get All Acceptance Test @HatemGamal by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an SemesterCourse this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by eriadhami** [comment]
> ## Service

> * SemesterCourse Service Add function @AgentEnder by Wednesday 12:00 AM - 11:59 PM PST
> * SemesterCourse Service Modify function @hiraldesai by Wednesday 12:00 AM - 11:59 PM PST
> * SemesterCourse Service Retrieve by Id function @tobidub by Wednesday 12:00 AM - 11:59 PM PST
> * SemesterCourse Service Retrieve All function @tajwal by Wednesday 12:00 AM - 11:59 PM PST
> * SemesterCourse Service Delete by Id function @devmanzur by Wednesday 12:00 AM - 11:59 PM PST
> 

I would be more than happy to help anyone with service implementation

**Comment by AgentEnder** [comment]
@eriadhami I am super busy today, if you want to take mine feel free, otherwise its going to be late tonight before I can do it.

**Comment by hiraldesai** [comment]
Same for me to @eriadhami - thank you!

**Comment by eriadhami** [comment]
> Same for me to @eriadhami - thank you!

Sorry I couldn't finish on time. I will do it later today

**Comment by hassanhabib** [comment]
Feature complete, thank you all <3 
https://github.com/hassanhabib/OtripleS/commit/dd99cb062618a5efc7488343dd04530bc4026a4e
