### ISSUE TITLE
Discuss StudentSemesterCourse Model

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#90]
Hi Everyone,
This is glue entity to build a relationship between Students and SemesterCourses as follows:

```csharp

    public class StudentSemesterCourse {
        public Guid StudentId {get; set;}
        public Guid SemesterCourse {get; set;}
    }
```

**Comment by AgentEnder** [comment]
I could see this glue entity containing the following add'l properties:

- Grade (percentage between 0/100)
- Status { Passed / Failed / In Progress }
- ICollection <AssignmentSubmission> SubmittedWork (once we have this entity)

**Comment by a-urel** [comment]
@hassanhabib @AgentEnder 
`Score` (`string`, like _A+, A, B..._) and `Attendence` (_days_ and/or _percentage_) properties are also needed.

**Comment by syedib** [comment]
We should maintain the **season** information about the semester which comes under whether it is **winter**, **summer**, **spring**. but I guess this should be included in **Semester** entity and not in **StudentSemesterCourse**

**Comment by a-urel** [comment]
@syedib yes, `Semester` is related to _calendar_ and _timetable_ concepts.

**Comment by tajwal** [comment]
1. sometime some students retake/repeat courses from previous semester, don't we need a column to show that  if this first time or student retake course from last semester?
2. We have score which is between 0 and 100, and than we have grade of its a,b,c or d, don't we need column for those here?

**Comment by a-urel** [comment]
@tajwal yes, `RepeatCount` is necessary.
I think we'll add a `Score` column for A, B, C...

**Comment by hassanhabib** [comment]
Thank you all for your contributions, here's an overview of our StudentSemesterCourse entity model and the StudentSemesterCourses this week:

```csharp

using System;
					
    public class StudentSemesterCourse : IAuditable
    {
        public Guid StudentId { get; set; }
        public Student Student { get; set; }

        public Guid SemesterCourseId { get; set; }
        public SemesterCourse SemesterCourse { get; set; }

        public string Grade { get; set; }
        public double Score { get; set; }
        public int Repeats { get; set; }
        public StudentSemesterCourseStatus Status { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
    }

    public enum StudentSemesterCourseStatus
    {
        Registered,
        InProgress,
        Dropped,
        Passed,
        Failed
    }

```
Now, let's talk about StudentSemesterCourses:

## Setup 

- StudentSemesterCourse Model Setup & Migrations with EF Core @hassanhabib Monday 12:00 AM - 11:59 PM PST [done]

## Broker

- StudentSemesterCourse Broker Select By Id function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Broker Select All function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST 
- StudentSemesterCourse Broker Insert function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST 
- StudentSemesterCourse Broker Update function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST 
- StudentSemesterCourse Broker Delete function @hassanhabib by Tuesday 12:00 AM - 11:59 PM PST 

## Service

- StudentSemesterCourse Service Add function @AgentEnder by Wednesday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Service Modify function @Mohamad-ali-8 by Wednesday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Service Retrieve by Id function @HatemGamal  by Wednesday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Service Retrieve All function @viralpandya by Wednesday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Service Delete by Id function @syedib  by Wednesday 12:00 AM - 11:59 PM PST

## Controller

- StudentSemesterCourse Controller Post endpoint @eriadhami by Thursday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Controller Get by Id endpoint @eriadhami     by Thursday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Controller Get All endpoint @eriadhami   by Thursday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Controller Update endpoint @eriadhami  by Thursday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Controller Delete endpoint @eriadhami   by Thursday 12:00 AM - 11:59 PM PST

## Acceptance Tests

- StudentSemesterCourse Post Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Update Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST
- StudentSemesterCourse Get All Acceptance Test @tajwal by Friday 12:00 AM - 11:59 PM PST


## Contribution Rules:
1. If you have a service task, make sure you commit a failing test, then commit making it pass and so on until your feature is complete (watch this video for reference: https://youtu.be/FLsHIDe3cNs)
2. All CRUD operations now have similar functionality in the StudentService, Teacher and Course Services, Brokers and Controllers - please follow the same pattern and guidelines.
3. This WIP Coding Standard https://github.com/hassanhabib/CSharpCodingStandard will be our guidance, it is a work in progress but it should give you a pretty good idea bout how our code should look like from guidelines and standardization standpoint.
4. Do not start your task before the designated time and make sure you finalize it at the expected time so others can build on top of your work.

If you haven't had an StudentSemesterCourse this week please make sure you engage in discussion for next week so I know you are active in this repo and you are going to be able to contribute to the project.

As soon as all these tasks are done, this issue will be closed.

Thank you all from the bottom of my heart <3 for your contributions, if you are stuck or unsure how to do a task, reach out to me literally on any social media platform you like, LinkedIn, Facebook, Whatsapp, Twitter or even Instagram or just ping me on gitter and I will be sure to response within 2 - 4 hours max.

**Comment by devmanzur** [comment]
:'( I didn't get any task.

**Comment by hassanhabib** [comment]
> :'( I didn't get any task.

@devmanzur just assigned a task to you.

**Comment by devmanzur** [comment]
Thanks, :D. I really like contributing to this project. I didn't know how to do unit tests before this project. Today I wrote unit tests in my office project for the first time (We never had tests in our projects). Felt great. Thank you @hassanhabib.

**Comment by AgentEnder** [comment]
@hassanhabib No new discussion this week?

**Comment by hassanhabib** [comment]
@AgentEnder coming out tonight - we will discuss some missing links between the entities we have created already.

**Comment by AgentEnder** [comment]
Great, thanks.

**Comment by eriadhami** [comment]
> * StudentSemesterCourse Service Modify function @Mohamad-ali-8 by Wednesday 12:00 AM - 11:59 PM PST
> * StudentSemesterCourse Service Retrieve by Id function @HatemGamal  by Wednesday 12:00 AM - 11:59 PM PST
> * StudentSemesterCourse Service Retrieve All function @devmanzur by Wednesday 12:00 AM - 11:59 PM PST

Guys, I will be happy to help with any of this.

**Comment by Mohamad-ali-8** [comment]
Yes please, can’t do it on time.
I thought I could...

Thanks
Mohamad

**Comment by tajwal** [comment]
@HatemGamal am waiting for StudentSemesterCourse Service Retrieve by Id function to finish acceptance tests.

**Comment by tajwal** [comment]
@eriadhami I am waiting for  StudentSemesterCourse Controller Get by Id endpoint.
